INSERT INTO town VALUES (1,1,'Alegría-Dulantzi');
INSERT INTO town VALUES (2,1,'Amurrio');
INSERT INTO town VALUES (3,1,'Añana');
INSERT INTO town VALUES (4,1,'Aramaio');
INSERT INTO town VALUES (5,1,'Armiñón');
INSERT INTO town VALUES (6,1,'Arraia-Maeztu');
INSERT INTO town VALUES (7,1,'Arrazua-Ubarrundia');
INSERT INTO town VALUES (8,1,'Artziniega');
INSERT INTO town VALUES (9,1,'Asparrena');
INSERT INTO town VALUES (10,1,'Ayala/Aiara');
INSERT INTO town VALUES (11,1,'Baños de Ebro/Mañueta');
INSERT INTO town VALUES (12,1,'Alegría-Dulantzi');
INSERT INTO town VALUES (13,1,'Amurrio');
INSERT INTO town VALUES (14,1,'Añana');
INSERT INTO town VALUES (15,1,'Aramaio');
INSERT INTO town VALUES (16,1,'Armiñón');
INSERT INTO town VALUES (17,1,'Arraia-Maeztu');
INSERT INTO town VALUES (18,1,'Arrazua-Ubarrundia');
INSERT INTO town VALUES (19,1,'Artziniega');
INSERT INTO town VALUES (20,1,'Asparrena');
INSERT INTO town VALUES (21,1,'Ayala/Aiara');
INSERT INTO town VALUES (22,1,'Baños de Ebro/Mañueta');
INSERT INTO town VALUES (23,1,'Barrundia');
INSERT INTO town VALUES (24,1,'Berantevilla');
INSERT INTO town VALUES (25,1,'Bernedo');
INSERT INTO town VALUES (26,1,'Campezo/Kanpezu');
INSERT INTO town VALUES (27,1,'Elburgo/Burgelu');
INSERT INTO town VALUES (28,1,'Elciego');
INSERT INTO town VALUES (29,1,'Elvillar/Bilar');
INSERT INTO town VALUES (30,1,'Harana/Valle de Arana');
INSERT INTO town VALUES (31,1,'Iruña Oka/Iruña de Oca');
INSERT INTO town VALUES (32,1,'Iruraiz-Gauna');
INSERT INTO town VALUES (33,1,'Kripan');
INSERT INTO town VALUES (34,1,'Kuartango');
INSERT INTO town VALUES (35,1,'Labastida/Bastida');
INSERT INTO town VALUES (36,1,'Lagrán');
INSERT INTO town VALUES (37,1,'Laguardia');
INSERT INTO town VALUES (38,1,'Lanciego/Lantziego');
INSERT INTO town VALUES (39,1,'Lantarón');
INSERT INTO town VALUES (40,1,'Lapuebla de Labarca');
INSERT INTO town VALUES (41,1,'Laudio/Llodio');
INSERT INTO town VALUES (42,1,'Legutiano');
INSERT INTO town VALUES (43,1,'Leza');
INSERT INTO town VALUES (44,1,'Moreda de Álava');
INSERT INTO town VALUES (45,1,'Navaridas');
INSERT INTO town VALUES (46,1,'Okondo');
INSERT INTO town VALUES (47,1,'Oyón-Oion');
INSERT INTO town VALUES (48,1,'Peñacerrada-Urizaharra');
INSERT INTO town VALUES (49,1,'Ribera Alta');
INSERT INTO town VALUES (50,1,'Ribera Baja/Erribera Beitia');
INSERT INTO town VALUES (51,1,'Salvatierra/Agurain');
INSERT INTO town VALUES (52,1,'Samaniego');
INSERT INTO town VALUES (53,1,'San Millán/Donemiliaga');
INSERT INTO town VALUES (54,1,'Urkabustaiz');
INSERT INTO town VALUES (55,1,'Valdegovía/Gaubea');
INSERT INTO town VALUES (56,1,'Villabuena de Álava/Eskuernaga');
INSERT INTO town VALUES (57,1,'Vitoria-Gasteiz');
INSERT INTO town VALUES (58,1,'Yécora/Iekora');
INSERT INTO town VALUES (59,1,'Zalduondo');
INSERT INTO town VALUES (60,1,'Zambrana');
INSERT INTO town VALUES (61,1,'Zigoitia');
INSERT INTO town VALUES (62,1,'Zuia');
INSERT INTO town VALUES (63,2,'Abengibre');
INSERT INTO town VALUES (64,2,'Alatoz');
INSERT INTO town VALUES (65,2,'Albacete');
INSERT INTO town VALUES (66,2,'Albatana');
INSERT INTO town VALUES (67,2,'Alborea');
INSERT INTO town VALUES (68,2,'Alcadozo');
INSERT INTO town VALUES (69,2,'Alcalá del Júcar');
INSERT INTO town VALUES (70,2,'Alcaraz');
INSERT INTO town VALUES (71,2,'Almansa');
INSERT INTO town VALUES (72,2,'Alpera');
INSERT INTO town VALUES (73,2,'Ayna');
INSERT INTO town VALUES (74,2,'Balazote');
INSERT INTO town VALUES (75,2,'Ballestero (El)');
INSERT INTO town VALUES (76,2,'Balsa de Ves');
INSERT INTO town VALUES (77,2,'Barrax');
INSERT INTO town VALUES (78,2,'Bienservida');
INSERT INTO town VALUES (79,2,'Bogarra');
INSERT INTO town VALUES (80,2,'Bonete');
INSERT INTO town VALUES (81,2,'Bonillo (El)');
INSERT INTO town VALUES (82,2,'Carcelén');
INSERT INTO town VALUES (83,2,'Casas de Juan Núñez');
INSERT INTO town VALUES (84,2,'Casas de Lázaro');
INSERT INTO town VALUES (85,2,'Casas de Ves');
INSERT INTO town VALUES (86,2,'Casas-Ibáñez');
INSERT INTO town VALUES (87,2,'Caudete');
INSERT INTO town VALUES (88,2,'Cenizate');
INSERT INTO town VALUES (89,2,'Chinchilla de Monte-Aragón');
INSERT INTO town VALUES (90,2,'Corral-Rubio');
INSERT INTO town VALUES (91,2,'Cotillas');
INSERT INTO town VALUES (92,2,'Elche de la Sierra');
INSERT INTO town VALUES (93,2,'Férez');
INSERT INTO town VALUES (94,2,'Fuensanta');
INSERT INTO town VALUES (95,2,'Fuente-Álamo');
INSERT INTO town VALUES (96,2,'Fuentealbilla');
INSERT INTO town VALUES (97,2,'Gineta (La)');
INSERT INTO town VALUES (98,2,'Golosalvo');
INSERT INTO town VALUES (99,2,'Hellín');
INSERT INTO town VALUES (100,2,'Herrera (La)');
INSERT INTO town VALUES (101,2,'Higueruela');
INSERT INTO town VALUES (102,2,'Hoya-Gonzalo');
INSERT INTO town VALUES (103,2,'Jorquera');
INSERT INTO town VALUES (104,2,'Letur');
INSERT INTO town VALUES (105,2,'Lezuza');
INSERT INTO town VALUES (106,2,'Liétor');
INSERT INTO town VALUES (107,2,'Madrigueras');
INSERT INTO town VALUES (108,2,'Mahora');
INSERT INTO town VALUES (109,2,'Masegoso');
INSERT INTO town VALUES (110,2,'Minaya');
INSERT INTO town VALUES (111,2,'Molinicos');
INSERT INTO town VALUES (112,2,'Montalvos');
INSERT INTO town VALUES (113,2,'Montealegre del Castillo');
INSERT INTO town VALUES (114,2,'Motilleja');
INSERT INTO town VALUES (115,2,'Munera');
INSERT INTO town VALUES (116,2,'Navas de Jorquera');
INSERT INTO town VALUES (117,2,'Nerpio');
INSERT INTO town VALUES (118,2,'Ontur');
INSERT INTO town VALUES (119,2,'Ossa de Montiel');
INSERT INTO town VALUES (120,2,'Paterna del Madera');
INSERT INTO town VALUES (121,2,'Peñas de San Pedro');
INSERT INTO town VALUES (122,2,'Peñascosa');
INSERT INTO town VALUES (123,2,'Pétrola');
INSERT INTO town VALUES (124,2,'Povedilla');
INSERT INTO town VALUES (125,2,'Pozo Cañada');
INSERT INTO town VALUES (126,2,'Pozohondo');
INSERT INTO town VALUES (127,2,'Pozo-Lorente');
INSERT INTO town VALUES (128,2,'Pozuelo');
INSERT INTO town VALUES (129,2,'Recueja (La)');
INSERT INTO town VALUES (130,2,'Riópar');
INSERT INTO town VALUES (131,2,'Robledo');
INSERT INTO town VALUES (132,2,'Roda (La)');
INSERT INTO town VALUES (133,2,'Salobre');
INSERT INTO town VALUES (134,2,'San Pedro');
INSERT INTO town VALUES (135,2,'Socovos');
INSERT INTO town VALUES (136,2,'Tarazona de la Mancha');
INSERT INTO town VALUES (137,2,'Tobarra');
INSERT INTO town VALUES (138,2,'Valdeganga');
INSERT INTO town VALUES (139,2,'Vianos');
INSERT INTO town VALUES (140,2,'Villa de Ves');
INSERT INTO town VALUES (141,2,'Villalgordo del Júcar');
INSERT INTO town VALUES (142,2,'Villamalea');
INSERT INTO town VALUES (143,2,'Villapalacios');
INSERT INTO town VALUES (144,2,'Villarrobledo');
INSERT INTO town VALUES (145,2,'Villatoya');
INSERT INTO town VALUES (146,2,'Villavaliente');
INSERT INTO town VALUES (147,2,'Villaverde de Guadalimar');
INSERT INTO town VALUES (148,2,'Viveros');
INSERT INTO town VALUES (149,2,'Yeste');
INSERT INTO town VALUES (150,3,'Adsubia');
INSERT INTO town VALUES (151,3,'Agost');
INSERT INTO town VALUES (152,3,'Agres');
INSERT INTO town VALUES (153,3,'Aigües');
INSERT INTO town VALUES (154,3,'Albatera');
INSERT INTO town VALUES (155,3,'Alcalalí');
INSERT INTO town VALUES (156,3,'Alcocer de Planes');
INSERT INTO town VALUES (157,3,'Alcoleja');
INSERT INTO town VALUES (158,3,'Alcoy/Alcoi');
INSERT INTO town VALUES (159,3,'Alfafara');
INSERT INTO town VALUES (160,3,'Alfàs del Pi ');
INSERT INTO town VALUES (161,3,'Algorfa');
INSERT INTO town VALUES (162,3,'Algueña');
INSERT INTO town VALUES (163,3,'Alicante/Alacant');
INSERT INTO town VALUES (164,3,'Almoradí');
INSERT INTO town VALUES (165,3,'Almudaina');
INSERT INTO town VALUES (166,3,'Alqueria deAsnar ');
INSERT INTO town VALUES (167,3,'Altea');
INSERT INTO town VALUES (168,3,'Aspe');
INSERT INTO town VALUES (169,3,'Balones');
INSERT INTO town VALUES (170,3,'Banyeres de Mariola');
INSERT INTO town VALUES (171,3,'Benasau');
INSERT INTO town VALUES (172,3,'Beneixama');
INSERT INTO town VALUES (173,3,'Benejúzar');
INSERT INTO town VALUES (174,3,'Benferri');
INSERT INTO town VALUES (175,3,'Beniarbeig');
INSERT INTO town VALUES (176,3,'Beniardá');
INSERT INTO town VALUES (177,3,'Beniarrés');
INSERT INTO town VALUES (178,3,'Benidoleig');
INSERT INTO town VALUES (179,3,'Benidorm');
INSERT INTO town VALUES (180,3,'Benifallim');
INSERT INTO town VALUES (181,3,'Benifato');
INSERT INTO town VALUES (182,3,'Benigembla');
INSERT INTO town VALUES (183,3,'Benijófar');
INSERT INTO town VALUES (184,3,'Benilloba');
INSERT INTO town VALUES (185,3,'Benillup');
INSERT INTO town VALUES (186,3,'Benimantell');
INSERT INTO town VALUES (187,3,'Benimarfull');
INSERT INTO town VALUES (188,3,'Benimassot');
INSERT INTO town VALUES (189,3,'Benimeli');
INSERT INTO town VALUES (190,3,'Benissa');
INSERT INTO town VALUES (191,3,'Benitachell/Poble Nou de Benitatxell (el)');
INSERT INTO town VALUES (192,3,'Biar');
INSERT INTO town VALUES (193,3,'Bigastro');
INSERT INTO town VALUES (194,3,'Bolulla');
INSERT INTO town VALUES (195,3,'Busot');
INSERT INTO town VALUES (196,3,'Callosa de Segura');
INSERT INTO town VALUES (197,3,'Callosa deEn Sarrià');
INSERT INTO town VALUES (198,3,'Calpe/Calp');
INSERT INTO town VALUES (199,3,'Campello (el)');
INSERT INTO town VALUES (200,3,'Campo de Mirra/Camp de Mirra (el)');
INSERT INTO town VALUES (201,3,'Cañada');
INSERT INTO town VALUES (202,3,'Castalla');
INSERT INTO town VALUES (203,3,'Castell de Castells');
INSERT INTO town VALUES (204,3,'Castell de Guadalest (el)');
INSERT INTO town VALUES (205,3,'Catral');
INSERT INTO town VALUES (206,3,'Cocentaina');
INSERT INTO town VALUES (207,3,'Confrides');
INSERT INTO town VALUES (208,3,'Cox');
INSERT INTO town VALUES (209,3,'Crevillent');
INSERT INTO town VALUES (210,3,'Daya Nueva');
INSERT INTO town VALUES (211,3,'Daya Vieja');
INSERT INTO town VALUES (212,3,'Dénia');
INSERT INTO town VALUES (213,3,'Dolores');
INSERT INTO town VALUES (214,3,'Elche/Elx');
INSERT INTO town VALUES (215,3,'Elda');
INSERT INTO town VALUES (216,3,'Facheca');
INSERT INTO town VALUES (217,3,'Famorca');
INSERT INTO town VALUES (218,3,'Finestrat');
INSERT INTO town VALUES (219,3,'Fondó de les Neus (el)');
INSERT INTO town VALUES (220,3,'Formentera del Segura');
INSERT INTO town VALUES (221,3,'Gaianes');
INSERT INTO town VALUES (222,3,'Gata de Gorgos');
INSERT INTO town VALUES (223,3,'Gorga');
INSERT INTO town VALUES (224,3,'Granja de Rocamora');
INSERT INTO town VALUES (225,3,'Guardamar del Segura');
INSERT INTO town VALUES (226,3,'Hondón de los Frailes');
INSERT INTO town VALUES (227,3,'Ibi');
INSERT INTO town VALUES (228,3,'Jacarilla');
INSERT INTO town VALUES (229,3,'Jalón/Xaló');
INSERT INTO town VALUES (230,3,'Jávea/Xàbia');
INSERT INTO town VALUES (231,3,'Jijona/Xixona');
INSERT INTO town VALUES (232,3,'Llíber');
INSERT INTO town VALUES (233,3,'Lorcha/Orxa ');
INSERT INTO town VALUES (234,3,'Millena');
INSERT INTO town VALUES (235,3,'Monforte del Cid');
INSERT INTO town VALUES (236,3,'Monóvar/Monòver');
INSERT INTO town VALUES (237,3,'Montesinos (Los)');
INSERT INTO town VALUES (238,3,'Murla');
INSERT INTO town VALUES (239,3,'Muro de Alcoy');
INSERT INTO town VALUES (240,3,'Mutxamel');
INSERT INTO town VALUES (241,3,'Novelda');
INSERT INTO town VALUES (242,3,'Nucia (la)');
INSERT INTO town VALUES (243,3,'Ondara');
INSERT INTO town VALUES (244,3,'Onil');
INSERT INTO town VALUES (245,3,'Orba');
INSERT INTO town VALUES (246,3,'Orihuela');
INSERT INTO town VALUES (247,3,'Orxeta');
INSERT INTO town VALUES (248,3,'Parcent');
INSERT INTO town VALUES (249,3,'Pedreguer');
INSERT INTO town VALUES (250,3,'Pego');
INSERT INTO town VALUES (251,3,'Penàguila');
INSERT INTO town VALUES (252,3,'Petrer');
INSERT INTO town VALUES (253,3,'Pilar de la Horadada');
INSERT INTO town VALUES (254,3,'Pinós (el)/Pinoso');
INSERT INTO town VALUES (255,3,'Planes');
INSERT INTO town VALUES (256,3,'Poblets (els)');
INSERT INTO town VALUES (257,3,'Polop');
INSERT INTO town VALUES (258,3,'Quatretondeta');
INSERT INTO town VALUES (259,3,'Rafal');
INSERT INTO town VALUES (260,3,'Ràfol deAlmúnia (El)');
INSERT INTO town VALUES (261,3,'Redován');
INSERT INTO town VALUES (262,3,'Relleu');
INSERT INTO town VALUES (263,3,'Rojales');
INSERT INTO town VALUES (264,3,'Romana (la)');
INSERT INTO town VALUES (265,3,'Sagra');
INSERT INTO town VALUES (266,3,'Salinas');
INSERT INTO town VALUES (267,3,'San Fulgencio');
INSERT INTO town VALUES (268,3,'San Isidro');
INSERT INTO town VALUES (269,3,'San Miguel de Salinas');
INSERT INTO town VALUES (270,3,'San Vicente del Raspeig/Sant Vicent del Raspeig');
INSERT INTO town VALUES (271,3,'Sanet y Negrals');
INSERT INTO town VALUES (272,3,'Sant Joan deAlacant');
INSERT INTO town VALUES (273,3,'Santa Pola');
INSERT INTO town VALUES (274,3,'Sax');
INSERT INTO town VALUES (275,3,'Sella');
INSERT INTO town VALUES (276,3,'Senija');
INSERT INTO town VALUES (277,3,'Tàrbena');
INSERT INTO town VALUES (278,3,'Teulada');
INSERT INTO town VALUES (279,3,'Tibi');
INSERT INTO town VALUES (280,3,'Tollos');
INSERT INTO town VALUES (281,3,'Tormos');
INSERT INTO town VALUES (282,3,'Torremanzanas/Torre de les Maçanes (la)');
INSERT INTO town VALUES (283,3,'Torrevieja');
INSERT INTO town VALUES (284,3,'Vall deAlcalà (la)');
INSERT INTO town VALUES (285,3,'Vall de Ebo');
INSERT INTO town VALUES (286,3,'Vall de Gallinera');
INSERT INTO town VALUES (287,3,'Vall de Laguar (la)');
INSERT INTO town VALUES (288,3,'Verger (el)');
INSERT INTO town VALUES (289,3,'Villajoyosa/Vila Joiosa (la)');
INSERT INTO town VALUES (290,3,'Villena');
INSERT INTO town VALUES (291,4,'Abla');
INSERT INTO town VALUES (292,4,'Abrucena');
INSERT INTO town VALUES (293,4,'Adra');
INSERT INTO town VALUES (294,4,'Albánchez');
INSERT INTO town VALUES (295,4,'Alboloduy');
INSERT INTO town VALUES (296,4,'Albox');
INSERT INTO town VALUES (297,4,'Alcolea');
INSERT INTO town VALUES (298,4,'Alcóntar');
INSERT INTO town VALUES (299,4,'Alcudia de Monteagud');
INSERT INTO town VALUES (300,4,'Alhabia');
INSERT INTO town VALUES (301,4,'Alhama de Almería');
INSERT INTO town VALUES (302,4,'Alicún');
INSERT INTO town VALUES (303,4,'Almería');
INSERT INTO town VALUES (304,4,'Almócita');
INSERT INTO town VALUES (305,4,'Alsodux');
INSERT INTO town VALUES (306,4,'Antas');
INSERT INTO town VALUES (307,4,'Arboleas');
INSERT INTO town VALUES (308,4,'Armuña de Almanzora');
INSERT INTO town VALUES (309,4,'Bacares');
INSERT INTO town VALUES (310,4,'Bayárcal');
INSERT INTO town VALUES (311,4,'Bayarque');
INSERT INTO town VALUES (312,4,'Bédar');
INSERT INTO town VALUES (313,4,'Beires');
INSERT INTO town VALUES (314,4,'Benahadux');
INSERT INTO town VALUES (315,4,'Benitagla');
INSERT INTO town VALUES (316,4,'Benizalón');
INSERT INTO town VALUES (317,4,'Bentarique');
INSERT INTO town VALUES (318,4,'Berja');
INSERT INTO town VALUES (319,4,'Canjáyar');
INSERT INTO town VALUES (320,4,'Cantoria');
INSERT INTO town VALUES (321,4,'Carboneras');
INSERT INTO town VALUES (322,4,'Castro de Filabres');
INSERT INTO town VALUES (323,4,'Chercos');
INSERT INTO town VALUES (324,4,'Chirivel');
INSERT INTO town VALUES (325,4,'Cóbdar');
INSERT INTO town VALUES (326,4,'Cuevas del Almanzora');
INSERT INTO town VALUES (327,4,'Dalías');
INSERT INTO town VALUES (328,4,'Ejido (El)');
INSERT INTO town VALUES (329,4,'Enix');
INSERT INTO town VALUES (330,4,'Felix');
INSERT INTO town VALUES (331,4,'Fines');
INSERT INTO town VALUES (332,4,'Fiñana');
INSERT INTO town VALUES (333,4,'Fondón');
INSERT INTO town VALUES (334,4,'Gádor');
INSERT INTO town VALUES (335,4,'Gallardos (Los)');
INSERT INTO town VALUES (336,4,'Garrucha');
INSERT INTO town VALUES (337,4,'Gérgal');
INSERT INTO town VALUES (338,4,'Huécija');
INSERT INTO town VALUES (339,4,'Huércal de Almería');
INSERT INTO town VALUES (340,4,'Huércal-Overa');
INSERT INTO town VALUES (341,4,'Illar');
INSERT INTO town VALUES (342,4,'Instinción');
INSERT INTO town VALUES (343,4,'Laroya');
INSERT INTO town VALUES (344,4,'Láujar de Andarax');
INSERT INTO town VALUES (345,4,'Líjar');
INSERT INTO town VALUES (346,4,'Lubrín');
INSERT INTO town VALUES (347,4,'Lucainena de las Torres');
INSERT INTO town VALUES (348,4,'Lúcar');
INSERT INTO town VALUES (349,4,'Macael');
INSERT INTO town VALUES (350,4,'María');
INSERT INTO town VALUES (351,4,'Mojácar');
INSERT INTO town VALUES (352,4,'Mojonera (La)');
INSERT INTO town VALUES (353,4,'Nacimiento');
INSERT INTO town VALUES (354,4,'Níjar');
INSERT INTO town VALUES (355,4,'Ohanes');
INSERT INTO town VALUES (356,4,'Olula de Castro');
INSERT INTO town VALUES (357,4,'Olula del Río');
INSERT INTO town VALUES (358,4,'Oria');
INSERT INTO town VALUES (359,4,'Padules');
INSERT INTO town VALUES (360,4,'Partaloa');
INSERT INTO town VALUES (361,4,'Paterna del Río');
INSERT INTO town VALUES (362,4,'Pechina');
INSERT INTO town VALUES (363,4,'Pulpí');
INSERT INTO town VALUES (364,4,'Purchena');
INSERT INTO town VALUES (365,4,'Rágol');
INSERT INTO town VALUES (366,4,'Rioja');
INSERT INTO town VALUES (367,4,'Roquetas de Mar');
INSERT INTO town VALUES (368,4,'Santa Cruz de Marchena');
INSERT INTO town VALUES (369,4,'Santa Fe de Mondújar');
INSERT INTO town VALUES (370,4,'Senés');
INSERT INTO town VALUES (371,4,'Serón');
INSERT INTO town VALUES (372,4,'Sierro');
INSERT INTO town VALUES (373,4,'Somontín');
INSERT INTO town VALUES (374,4,'Sorbas');
INSERT INTO town VALUES (375,4,'Suflí');
INSERT INTO town VALUES (376,4,'Tabernas');
INSERT INTO town VALUES (377,4,'Taberno');
INSERT INTO town VALUES (378,4,'Tahal');
INSERT INTO town VALUES (379,4,'Terque');
INSERT INTO town VALUES (380,4,'Tíjola');
INSERT INTO town VALUES (381,4,'Tres Villas (Las)');
INSERT INTO town VALUES (382,4,'Turre');
INSERT INTO town VALUES (383,4,'Turrillas');
INSERT INTO town VALUES (384,4,'Uleila del Campo');
INSERT INTO town VALUES (385,4,'Urrácal');
INSERT INTO town VALUES (386,4,'Velefique');
INSERT INTO town VALUES (387,4,'Vélez-Blanco');
INSERT INTO town VALUES (388,4,'Vélez-Rubio');
INSERT INTO town VALUES (389,4,'Vera');
INSERT INTO town VALUES (390,4,'Viator');
INSERT INTO town VALUES (391,4,'Vícar');
INSERT INTO town VALUES (392,4,'Zurgena');
INSERT INTO town VALUES (393,5,'Adanero');
INSERT INTO town VALUES (394,5,'Adrada (La)');
INSERT INTO town VALUES (395,5,'Albornos');
INSERT INTO town VALUES (396,5,'Aldeanueva de Santa Cruz');
INSERT INTO town VALUES (397,5,'Aldeaseca');
INSERT INTO town VALUES (398,5,'Aldehuela (La)');
INSERT INTO town VALUES (399,5,'Amavida');
INSERT INTO town VALUES (400,5,'Arenal (El)');
INSERT INTO town VALUES (401,5,'Arenas de San Pedro');
INSERT INTO town VALUES (402,5,'Arevalillo');
INSERT INTO town VALUES (403,5,'Arévalo');
INSERT INTO town VALUES (404,5,'Aveinte');
INSERT INTO town VALUES (405,5,'Avellaneda');
INSERT INTO town VALUES (406,5,'Ávila');
INSERT INTO town VALUES (407,5,'Barco de Ávila (El)');
INSERT INTO town VALUES (408,5,'Barraco (El)');
INSERT INTO town VALUES (409,5,'Barromán');
INSERT INTO town VALUES (410,5,'Becedas');
INSERT INTO town VALUES (411,5,'Becedillas');
INSERT INTO town VALUES (412,5,'Bercial de Zapardiel');
INSERT INTO town VALUES (413,5,'Berlanas (Las)');
INSERT INTO town VALUES (414,5,'Bernuy-Zapardiel');
INSERT INTO town VALUES (415,5,'Berrocalejo de Aragona');
INSERT INTO town VALUES (416,5,'Blascomillán');
INSERT INTO town VALUES (417,5,'Blasconuño de Matacabras');
INSERT INTO town VALUES (418,5,'Blascosancho');
INSERT INTO town VALUES (419,5,'Bohodón (El)');
INSERT INTO town VALUES (420,5,'Bohoyo');
INSERT INTO town VALUES (421,5,'Bonilla de la Sierra');
INSERT INTO town VALUES (422,5,'Brabos');
INSERT INTO town VALUES (423,5,'Bularros');
INSERT INTO town VALUES (424,5,'Burgohondo');
INSERT INTO town VALUES (425,5,'Cabezas de Alambre');
INSERT INTO town VALUES (426,5,'Cabezas del Pozo');
INSERT INTO town VALUES (427,5,'Cabezas del Villar');
INSERT INTO town VALUES (428,5,'Cabizuela');
INSERT INTO town VALUES (429,5,'Canales');
INSERT INTO town VALUES (430,5,'Candeleda');
INSERT INTO town VALUES (431,5,'Cantiveros');
INSERT INTO town VALUES (432,5,'Cardeñosa');
INSERT INTO town VALUES (433,5,'Carrera (La)');
INSERT INTO town VALUES (434,5,'Casas del Puerto');
INSERT INTO town VALUES (435,5,'Casasola');
INSERT INTO town VALUES (436,5,'Casavieja');
INSERT INTO town VALUES (437,5,'Casillas');
INSERT INTO town VALUES (438,5,'Castellanos de Zapardiel');
INSERT INTO town VALUES (439,5,'Cebreros');
INSERT INTO town VALUES (440,5,'Cepeda la Mora');
INSERT INTO town VALUES (441,5,'Chamartín');
INSERT INTO town VALUES (442,5,'Cillán');
INSERT INTO town VALUES (443,5,'Cisla');
INSERT INTO town VALUES (444,5,'Colilla (La)');
INSERT INTO town VALUES (445,5,'Collado de Contreras');
INSERT INTO town VALUES (446,5,'Collado del Mirón');
INSERT INTO town VALUES (447,5,'Constanzana');
INSERT INTO town VALUES (448,5,'Crespos');
INSERT INTO town VALUES (449,5,'Cuevas del Valle');
INSERT INTO town VALUES (450,5,'Diego del Carpio');
INSERT INTO town VALUES (451,5,'Donjimeno');
INSERT INTO town VALUES (452,5,'Donvidas');
INSERT INTO town VALUES (453,5,'Espinosa de los Caballeros');
INSERT INTO town VALUES (454,5,'Flores de Ávila');
INSERT INTO town VALUES (455,5,'Fontiveros');
INSERT INTO town VALUES (456,5,'Fresnedilla');
INSERT INTO town VALUES (457,5,'Fresno (El)');
INSERT INTO town VALUES (458,5,'Fuente el Saúz');
INSERT INTO town VALUES (459,5,'Fuentes de Año');
INSERT INTO town VALUES (460,5,'Gallegos de Altamiros');
INSERT INTO town VALUES (461,5,'Gallegos de Sobrinos');
INSERT INTO town VALUES (462,5,'Garganta del Villar');
INSERT INTO town VALUES (463,5,'Gavilanes');
INSERT INTO town VALUES (464,5,'Gemuño');
INSERT INTO town VALUES (465,5,'Gil García');
INSERT INTO town VALUES (466,5,'Gilbuena');
INSERT INTO town VALUES (467,5,'Gimialcón');
INSERT INTO town VALUES (468,5,'Gotarrendura');
INSERT INTO town VALUES (469,5,'Grandes y San Martín');
INSERT INTO town VALUES (470,5,'Guisando');
INSERT INTO town VALUES (471,5,'Gutierre-Muñoz');
INSERT INTO town VALUES (472,5,'Hernansancho');
INSERT INTO town VALUES (473,5,'Herradón de Pinares');
INSERT INTO town VALUES (474,5,'Herreros de Suso');
INSERT INTO town VALUES (475,5,'Higuera de las Dueñas');
INSERT INTO town VALUES (476,5,'Hija de Dios (La)');
INSERT INTO town VALUES (477,5,'Horcajada (La)');
INSERT INTO town VALUES (478,5,'Horcajo de las Torres');
INSERT INTO town VALUES (479,5,'Hornillo (El)');
INSERT INTO town VALUES (480,5,'Hoyo de Pinares (El)');
INSERT INTO town VALUES (481,5,'Hoyocasero');
INSERT INTO town VALUES (482,5,'Hoyorredondo');
INSERT INTO town VALUES (483,5,'Hoyos de Miguel Muñoz');
INSERT INTO town VALUES (484,5,'Hoyos del Collado');
INSERT INTO town VALUES (485,5,'Hoyos del Espino');
INSERT INTO town VALUES (486,5,'Hurtumpascual');
INSERT INTO town VALUES (487,5,'Junciana');
INSERT INTO town VALUES (488,5,'Langa');
INSERT INTO town VALUES (489,5,'Lanzahíta');
INSERT INTO town VALUES (490,5,'Llanos de Tormes (Los)');
INSERT INTO town VALUES (491,5,'Losar del Barco (El)');
INSERT INTO town VALUES (492,5,'Madrigal de las Altas Torres');
INSERT INTO town VALUES (493,5,'Maello');
INSERT INTO town VALUES (494,5,'Malpartida de Corneja');
INSERT INTO town VALUES (495,5,'Mamblas');
INSERT INTO town VALUES (496,5,'Mancera de Arriba');
INSERT INTO town VALUES (497,5,'Manjabálago');
INSERT INTO town VALUES (498,5,'Marlín');
INSERT INTO town VALUES (499,5,'Martiherrero');
INSERT INTO town VALUES (500,5,'Martínez');
INSERT INTO town VALUES (501,5,'Mediana de Voltoya');
INSERT INTO town VALUES (502,5,'Medinilla');
INSERT INTO town VALUES (503,5,'Mengamuñoz');
INSERT INTO town VALUES (504,5,'Mesegar de Corneja');
INSERT INTO town VALUES (505,5,'Mijares');
INSERT INTO town VALUES (506,5,'Mingorría');
INSERT INTO town VALUES (507,5,'Mirón (El)');
INSERT INTO town VALUES (508,5,'Mironcillo');
INSERT INTO town VALUES (509,5,'Mirueña de los Infanzones');
INSERT INTO town VALUES (510,5,'Mombeltrán');
INSERT INTO town VALUES (511,5,'Monsalupe');
INSERT INTO town VALUES (512,5,'Moraleja de Matacabras');
INSERT INTO town VALUES (513,5,'Muñana');
INSERT INTO town VALUES (514,5,'Muñico');
INSERT INTO town VALUES (515,5,'Muñogalindo');
INSERT INTO town VALUES (516,5,'Muñogrande');
INSERT INTO town VALUES (517,5,'Muñomer del Peco');
INSERT INTO town VALUES (518,5,'Muñopepe');
INSERT INTO town VALUES (519,5,'Muñosancho');
INSERT INTO town VALUES (520,5,'Muñotello');
INSERT INTO town VALUES (521,5,'Narrillos del Álamo');
INSERT INTO town VALUES (522,5,'Narrillos del Rebollar');
INSERT INTO town VALUES (523,5,'Narros de Saldueña');
INSERT INTO town VALUES (524,5,'Narros del Castillo');
INSERT INTO town VALUES (525,5,'Narros del Puerto');
INSERT INTO town VALUES (526,5,'Nava de Arévalo');
INSERT INTO town VALUES (527,5,'Nava del Barco');
INSERT INTO town VALUES (528,5,'Navacepedilla de Corneja');
INSERT INTO town VALUES (529,5,'Navadijos');
INSERT INTO town VALUES (530,5,'Navaescurial');
INSERT INTO town VALUES (531,5,'Navahondilla');
INSERT INTO town VALUES (532,5,'Navalacruz');
INSERT INTO town VALUES (533,5,'Navalmoral');
INSERT INTO town VALUES (534,5,'Navalonguilla');
INSERT INTO town VALUES (535,5,'Navalosa');
INSERT INTO town VALUES (536,5,'Navalperal de Pinares');
INSERT INTO town VALUES (537,5,'Navalperal de Tormes');
INSERT INTO town VALUES (538,5,'Navaluenga');
INSERT INTO town VALUES (539,5,'Navaquesera');
INSERT INTO town VALUES (540,5,'Navarredonda de Gredos');
INSERT INTO town VALUES (541,5,'Navarredondilla');
INSERT INTO town VALUES (542,5,'Navarrevisca');
INSERT INTO town VALUES (543,5,'Navas del Marqués (Las)');
INSERT INTO town VALUES (544,5,'Navatalgordo');
INSERT INTO town VALUES (545,5,'Navatejares');
INSERT INTO town VALUES (546,5,'Neila de San Miguel');
INSERT INTO town VALUES (547,5,'Niharra');
INSERT INTO town VALUES (548,5,'Ojos-Albos');
INSERT INTO town VALUES (549,5,'Orbita');
INSERT INTO town VALUES (550,5,'Oso (El)');
INSERT INTO town VALUES (551,5,'Padiernos');
INSERT INTO town VALUES (552,5,'Pajares de Adaja');
INSERT INTO town VALUES (553,5,'Palacios de Goda');
INSERT INTO town VALUES (554,5,'Papatrigo');
INSERT INTO town VALUES (555,5,'Parral (El)');
INSERT INTO town VALUES (556,5,'Pascualcobo');
INSERT INTO town VALUES (557,5,'Pedro Bernardo');
INSERT INTO town VALUES (558,5,'Pedro-Rodríguez');
INSERT INTO town VALUES (559,5,'Peguerinos');
INSERT INTO town VALUES (560,5,'Peñalba de Ávila');
INSERT INTO town VALUES (561,5,'Piedrahíta');
INSERT INTO town VALUES (562,5,'Piedralaves');
INSERT INTO town VALUES (563,5,'Poveda');
INSERT INTO town VALUES (564,5,'Poyales del Hoyo');
INSERT INTO town VALUES (565,5,'Pozanco');
INSERT INTO town VALUES (566,5,'Pradosegar');
INSERT INTO town VALUES (567,5,'Puerto Castilla');
INSERT INTO town VALUES (568,5,'Rasueros');
INSERT INTO town VALUES (569,5,'Riocabado');
INSERT INTO town VALUES (570,5,'Riofrío');
INSERT INTO town VALUES (571,5,'Rivilla de Barajas');
INSERT INTO town VALUES (572,5,'Salobral');
INSERT INTO town VALUES (573,5,'Salvadiós');
INSERT INTO town VALUES (574,5,'San Bartolomé de Béjar');
INSERT INTO town VALUES (575,5,'San Bartolomé de Corneja');
INSERT INTO town VALUES (576,5,'San Bartolomé de Pinares');
INSERT INTO town VALUES (577,5,'San Esteban de los Patos');
INSERT INTO town VALUES (578,5,'San Esteban de Zapardiel');
INSERT INTO town VALUES (579,5,'San Esteban del Valle');
INSERT INTO town VALUES (580,5,'San García de Ingelmos');
INSERT INTO town VALUES (581,5,'San Juan de Gredos');
INSERT INTO town VALUES (582,5,'San Juan de la Encinilla');
INSERT INTO town VALUES (583,5,'San Juan de la Nava');
INSERT INTO town VALUES (584,5,'San Juan del Molinillo');
INSERT INTO town VALUES (585,5,'San Juan del Olmo');
INSERT INTO town VALUES (586,5,'San Lorenzo de Tormes');
INSERT INTO town VALUES (587,5,'San Martín de la Vega del Alberche');
INSERT INTO town VALUES (588,5,'San Martín del Pimpollar');
INSERT INTO town VALUES (589,5,'San Miguel de Corneja');
INSERT INTO town VALUES (590,5,'San Miguel de Serrezuela');
INSERT INTO town VALUES (591,5,'San Pascual');
INSERT INTO town VALUES (592,5,'San Pedro del Arroyo');
INSERT INTO town VALUES (593,5,'San Vicente de Arévalo');
INSERT INTO town VALUES (594,5,'Sanchidrián');
INSERT INTO town VALUES (595,5,'Sanchorreja');
INSERT INTO town VALUES (596,5,'Santa Cruz de Pinares');
INSERT INTO town VALUES (597,5,'Santa Cruz del Valle');
INSERT INTO town VALUES (598,5,'Santa María de los Caballeros');
INSERT INTO town VALUES (599,5,'Santa María del Arroyo');
INSERT INTO town VALUES (600,5,'Santa María del Berrocal');
INSERT INTO town VALUES (601,5,'Santa María del Cubillo');
INSERT INTO town VALUES (602,5,'Santa María del Tiétar');
INSERT INTO town VALUES (603,5,'Santiago del Collado');
INSERT INTO town VALUES (604,5,'Santiago del Tormes');
INSERT INTO town VALUES (605,5,'Santo Domingo de las Posadas');
INSERT INTO town VALUES (606,5,'Santo Tomé de Zabarcos');
INSERT INTO town VALUES (607,5,'Serrada (La)');
INSERT INTO town VALUES (608,5,'Serranillos');
INSERT INTO town VALUES (609,5,'Sigeres');
INSERT INTO town VALUES (610,5,'Sinlabajos');
INSERT INTO town VALUES (611,5,'Solana de Ávila');
INSERT INTO town VALUES (612,5,'Solana de Rioalmar');
INSERT INTO town VALUES (613,5,'Solosancho');
INSERT INTO town VALUES (614,5,'Sotalbo');
INSERT INTO town VALUES (615,5,'Sotillo de la Adrada');
INSERT INTO town VALUES (616,5,'Tiemblo (El)');
INSERT INTO town VALUES (617,5,'Tiñosillos');
INSERT INTO town VALUES (618,5,'Tolbaños');
INSERT INTO town VALUES (619,5,'Tormellas');
INSERT INTO town VALUES (620,5,'Tornadizos de Ávila');
INSERT INTO town VALUES (621,5,'Torre (La)');
INSERT INTO town VALUES (622,5,'Tórtoles');
INSERT INTO town VALUES (623,5,'Umbrías');
INSERT INTO town VALUES (624,5,'Vadillo de la Sierra');
INSERT INTO town VALUES (625,5,'Valdecasa');
INSERT INTO town VALUES (626,5,'Vega de Santa María');
INSERT INTO town VALUES (627,5,'Velayos');
INSERT INTO town VALUES (628,5,'Villaflor');
INSERT INTO town VALUES (629,5,'Villafranca de la Sierra');
INSERT INTO town VALUES (630,5,'Villanueva de Ávila');
INSERT INTO town VALUES (631,5,'Villanueva de Gómez');
INSERT INTO town VALUES (632,5,'Villanueva del Aceral');
INSERT INTO town VALUES (633,5,'Villanueva del Campillo');
INSERT INTO town VALUES (634,5,'Villar de Corneja');
INSERT INTO town VALUES (635,5,'Villarejo del Valle');
INSERT INTO town VALUES (636,5,'Villatoro');
INSERT INTO town VALUES (637,5,'Viñegra de Moraña');
INSERT INTO town VALUES (638,5,'Vita');
INSERT INTO town VALUES (639,5,'Zapardiel de la Cañada');
INSERT INTO town VALUES (640,5,'Zapardiel de la Ribera');
INSERT INTO town VALUES (641,6,'Acedera');
INSERT INTO town VALUES (642,6,'Aceuchal');
INSERT INTO town VALUES (643,6,'Ahillones');
INSERT INTO town VALUES (644,6,'Alange');
INSERT INTO town VALUES (645,6,'Albuera (La)');
INSERT INTO town VALUES (646,6,'Alburquerque');
INSERT INTO town VALUES (647,6,'Alconchel');
INSERT INTO town VALUES (648,6,'Alconera');
INSERT INTO town VALUES (649,6,'Aljucén');
INSERT INTO town VALUES (650,6,'Almendral');
INSERT INTO town VALUES (651,6,'Almendralejo');
INSERT INTO town VALUES (652,6,'Arroyo de San Serván');
INSERT INTO town VALUES (653,6,'Atalaya');
INSERT INTO town VALUES (654,6,'Azuaga');
INSERT INTO town VALUES (655,6,'Badajoz');
INSERT INTO town VALUES (656,6,'Barcarrota');
INSERT INTO town VALUES (657,6,'Baterno');
INSERT INTO town VALUES (658,6,'Benquerencia de la Serena');
INSERT INTO town VALUES (659,6,'Berlanga');
INSERT INTO town VALUES (660,6,'Bienvenida');
INSERT INTO town VALUES (661,6,'Bodonal de la Sierra');
INSERT INTO town VALUES (662,6,'Burguillos del Cerro');
INSERT INTO town VALUES (663,6,'Cabeza del Buey');
INSERT INTO town VALUES (664,6,'Cabeza la Vaca');
INSERT INTO town VALUES (665,6,'Calamonte');
INSERT INTO town VALUES (666,6,'Calera de León');
INSERT INTO town VALUES (667,6,'Calzadilla de los Barros');
INSERT INTO town VALUES (668,6,'Campanario');
INSERT INTO town VALUES (669,6,'Campillo de Llerena');
INSERT INTO town VALUES (670,6,'Capilla');
INSERT INTO town VALUES (671,6,'Carmonita');
INSERT INTO town VALUES (672,6,'Carrascalejo (El)');
INSERT INTO town VALUES (673,6,'Casas de Don Pedro');
INSERT INTO town VALUES (674,6,'Casas de Reina');
INSERT INTO town VALUES (675,6,'Castilblanco');
INSERT INTO town VALUES (676,6,'Castuera');
INSERT INTO town VALUES (677,6,'Cheles');
INSERT INTO town VALUES (678,6,'Codosera (La)');
INSERT INTO town VALUES (679,6,'Cordobilla de Lácara');
INSERT INTO town VALUES (680,6,'Coronada (La)');
INSERT INTO town VALUES (681,6,'Corte de Peleas');
INSERT INTO town VALUES (682,6,'Cristina');
INSERT INTO town VALUES (683,6,'Don Álvaro');
INSERT INTO town VALUES (684,6,'Don Benito');
INSERT INTO town VALUES (685,6,'Entrín Bajo');
INSERT INTO town VALUES (686,6,'Esparragalejo');
INSERT INTO town VALUES (687,6,'Esparragosa de la Serena');
INSERT INTO town VALUES (688,6,'Esparragosa de Lares');
INSERT INTO town VALUES (689,6,'Feria');
INSERT INTO town VALUES (690,6,'Fregenal de la Sierra');
INSERT INTO town VALUES (691,6,'Fuenlabrada de los Montes');
INSERT INTO town VALUES (692,6,'Fuente de Cantos');
INSERT INTO town VALUES (693,6,'Fuente del Arco');
INSERT INTO town VALUES (694,6,'Fuente del Maestre');
INSERT INTO town VALUES (695,6,'Fuentes de León');
INSERT INTO town VALUES (696,6,'Garbayuela');
INSERT INTO town VALUES (697,6,'Garlitos');
INSERT INTO town VALUES (698,6,'Garrovilla (La)');
INSERT INTO town VALUES (699,6,'Granja de Torrehermosa');
INSERT INTO town VALUES (700,6,'Guareña');
INSERT INTO town VALUES (701,6,'Haba (La)');
INSERT INTO town VALUES (702,6,'Helechosa de los Montes');
INSERT INTO town VALUES (703,6,'Herrera del Duque');
INSERT INTO town VALUES (704,6,'Higuera de la Serena');
INSERT INTO town VALUES (705,6,'Higuera de Llerena');
INSERT INTO town VALUES (706,6,'Higuera de Vargas');
INSERT INTO town VALUES (707,6,'Higuera la Real');
INSERT INTO town VALUES (708,6,'Hinojosa del Valle');
INSERT INTO town VALUES (709,6,'Hornachos');
INSERT INTO town VALUES (710,6,'Jerez de los Caballeros');
INSERT INTO town VALUES (711,6,'Lapa (La)');
INSERT INTO town VALUES (712,6,'Llera');
INSERT INTO town VALUES (713,6,'Llerena');
INSERT INTO town VALUES (714,6,'Lobón');
INSERT INTO town VALUES (715,6,'Magacela');
INSERT INTO town VALUES (716,6,'Maguilla');
INSERT INTO town VALUES (717,6,'Malcocinado');
INSERT INTO town VALUES (718,6,'Malpartida de la Serena');
INSERT INTO town VALUES (719,6,'Manchita');
INSERT INTO town VALUES (720,6,'Medellín');
INSERT INTO town VALUES (721,6,'Medina de las Torres');
INSERT INTO town VALUES (722,6,'Mengabril');
INSERT INTO town VALUES (723,6,'Mérida');
INSERT INTO town VALUES (724,6,'Mirandilla');
INSERT INTO town VALUES (725,6,'Monesterio');
INSERT INTO town VALUES (726,6,'Montemolín');
INSERT INTO town VALUES (727,6,'Monterrubio de la Serena');
INSERT INTO town VALUES (728,6,'Montijo');
INSERT INTO town VALUES (729,6,'Morera (La)');
INSERT INTO town VALUES (730,6,'Nava de Santiago (La)');
INSERT INTO town VALUES (731,6,'Navalvillar de Pela');
INSERT INTO town VALUES (732,6,'Nogales');
INSERT INTO town VALUES (733,6,'Oliva de la Frontera');
INSERT INTO town VALUES (734,6,'Oliva de Mérida');
INSERT INTO town VALUES (735,6,'Olivenza');
INSERT INTO town VALUES (736,6,'Orellana de la Sierra');
INSERT INTO town VALUES (737,6,'Orellana la Vieja');
INSERT INTO town VALUES (738,6,'Palomas');
INSERT INTO town VALUES (739,6,'Parra (La)');
INSERT INTO town VALUES (740,6,'Peñalsordo');
INSERT INTO town VALUES (741,6,'Peraleda del Zaucejo');
INSERT INTO town VALUES (742,6,'Puebla de Alcocer');
INSERT INTO town VALUES (743,6,'Puebla de la Calzada');
INSERT INTO town VALUES (744,6,'Puebla de la Reina');
INSERT INTO town VALUES (745,6,'Puebla de Obando');
INSERT INTO town VALUES (746,6,'Puebla de Sancho Pérez');
INSERT INTO town VALUES (747,6,'Puebla del Maestre');
INSERT INTO town VALUES (748,6,'Puebla del Prior');
INSERT INTO town VALUES (749,6,'Pueblonuevo del Guadiana');
INSERT INTO town VALUES (750,6,'Quintana de la Serena');
INSERT INTO town VALUES (751,6,'Reina');
INSERT INTO town VALUES (752,6,'Rena');
INSERT INTO town VALUES (753,6,'Retamal de Llerena');
INSERT INTO town VALUES (754,6,'Ribera del Fresno');
INSERT INTO town VALUES (755,6,'Risco');
INSERT INTO town VALUES (756,6,'Roca de la Sierra (La)');
INSERT INTO town VALUES (757,6,'Salvaleón');
INSERT INTO town VALUES (758,6,'Salvatierra de los Barros');
INSERT INTO town VALUES (759,6,'San Pedro de Mérida');
INSERT INTO town VALUES (760,6,'San Vicente de Alcántara');
INSERT INTO town VALUES (761,6,'Sancti-Spíritus');
INSERT INTO town VALUES (762,6,'Santa Amalia');
INSERT INTO town VALUES (763,6,'Santa Marta');
INSERT INTO town VALUES (764,6,'Santos de Maimona (Los)');
INSERT INTO town VALUES (765,6,'Segura de León');
INSERT INTO town VALUES (766,6,'Siruela');
INSERT INTO town VALUES (767,6,'Solana de los Barros');
INSERT INTO town VALUES (768,6,'Talarrubias');
INSERT INTO town VALUES (769,6,'Talavera la Real');
INSERT INTO town VALUES (770,6,'Táliga');
INSERT INTO town VALUES (771,6,'Tamurejo');
INSERT INTO town VALUES (772,6,'Torre de Miguel Sesmero');
INSERT INTO town VALUES (773,6,'Torremayor');
INSERT INTO town VALUES (774,6,'Torremejía');
INSERT INTO town VALUES (775,6,'Trasierra');
INSERT INTO town VALUES (776,6,'Trujillanos');
INSERT INTO town VALUES (777,6,'Usagre');
INSERT INTO town VALUES (778,6,'Valdecaballeros');
INSERT INTO town VALUES (779,6,'Valdelacalzada');
INSERT INTO town VALUES (780,6,'Valdetorres');
INSERT INTO town VALUES (781,6,'Valencia de las Torres');
INSERT INTO town VALUES (782,6,'Valencia del Mombuey');
INSERT INTO town VALUES (783,6,'Valencia del Ventoso');
INSERT INTO town VALUES (784,6,'Valle de la Serena');
INSERT INTO town VALUES (785,6,'Valle de Matamoros');
INSERT INTO town VALUES (786,6,'Valle de Santa Ana');
INSERT INTO town VALUES (787,6,'Valverde de Burguillos');
INSERT INTO town VALUES (788,6,'Valverde de Leganés');
INSERT INTO town VALUES (789,6,'Valverde de Llerena');
INSERT INTO town VALUES (790,6,'Valverde de Mérida');
INSERT INTO town VALUES (791,6,'Villafranca de los Barros');
INSERT INTO town VALUES (792,6,'Villagarcía de la Torre');
INSERT INTO town VALUES (793,6,'Villagonzalo');
INSERT INTO town VALUES (794,6,'Villalba de los Barros');
INSERT INTO town VALUES (795,6,'Villanueva de la Serena');
INSERT INTO town VALUES (796,6,'Villanueva del Fresno');
INSERT INTO town VALUES (797,6,'Villar de Rena');
INSERT INTO town VALUES (798,6,'Villar del Rey');
INSERT INTO town VALUES (799,6,'Villarta de los Montes');
INSERT INTO town VALUES (800,6,'Zafra');
INSERT INTO town VALUES (801,6,'Zahínos');
INSERT INTO town VALUES (802,6,'Zalamea de la Serena');
INSERT INTO town VALUES (803,6,'Zarza (La)');
INSERT INTO town VALUES (804,6,'Zarza-Capilla');
INSERT INTO town VALUES (805,7,'Alaior');
INSERT INTO town VALUES (806,7,'Alaró');
INSERT INTO town VALUES (807,7,'Alcúdia');
INSERT INTO town VALUES (808,7,'Algaida');
INSERT INTO town VALUES (809,7,'Andratx');
INSERT INTO town VALUES (810,7,'Ariany');
INSERT INTO town VALUES (811,7,'Artà');
INSERT INTO town VALUES (812,7,'Banyalbufar');
INSERT INTO town VALUES (813,7,'Binissalem');
INSERT INTO town VALUES (814,7,'Búger');
INSERT INTO town VALUES (815,7,'Bunyola');
INSERT INTO town VALUES (816,7,'Calvià');
INSERT INTO town VALUES (817,7,'Campanet');
INSERT INTO town VALUES (818,7,'Campos');
INSERT INTO town VALUES (819,7,'Capdepera');
INSERT INTO town VALUES (820,7,'Castell (Es)');
INSERT INTO town VALUES (821,7,'Ciutadella de Menorca');
INSERT INTO town VALUES (822,7,'Consell');
INSERT INTO town VALUES (823,7,'Costitx');
INSERT INTO town VALUES (824,7,'Deyá');
INSERT INTO town VALUES (825,7,'Eivissa');
INSERT INTO town VALUES (826,7,'Escorca');
INSERT INTO town VALUES (827,7,'Esporles');
INSERT INTO town VALUES (828,7,'Estellencs');
INSERT INTO town VALUES (829,7,'Felanitx');
INSERT INTO town VALUES (830,7,'Ferreries');
INSERT INTO town VALUES (831,7,'Formentera');
INSERT INTO town VALUES (832,7,'Fornalutx');
INSERT INTO town VALUES (833,7,'Inca');
INSERT INTO town VALUES (834,7,'Lloret de Vistalegre');
INSERT INTO town VALUES (835,7,'Lloseta');
INSERT INTO town VALUES (836,7,'Llubí');
INSERT INTO town VALUES (837,7,'Llucmajor');
INSERT INTO town VALUES (838,7,'Manacor');
INSERT INTO town VALUES (839,7,'Mancor de la Vall');
INSERT INTO town VALUES (840,7,'Maó');
INSERT INTO town VALUES (841,7,'Maria de la Salut');
INSERT INTO town VALUES (842,7,'Marratxí');
INSERT INTO town VALUES (843,7,'Mercadal (Es)');
INSERT INTO town VALUES (844,7,'Migjorn Gran (Es)');
INSERT INTO town VALUES (845,7,'Montuïri');
INSERT INTO town VALUES (846,7,'Muro');
INSERT INTO town VALUES (847,7,'Palma de Mallorca');
INSERT INTO town VALUES (848,7,'Petra');
INSERT INTO town VALUES (849,7,'Pobla (Sa)');
INSERT INTO town VALUES (850,7,'Pollença');
INSERT INTO town VALUES (851,7,'Porreres');
INSERT INTO town VALUES (852,7,'Puigpunyent');
INSERT INTO town VALUES (853,7,'Salines (Ses)');
INSERT INTO town VALUES (854,7,'Sant Antoni de Portmany');
INSERT INTO town VALUES (855,7,'Sant Joan');
INSERT INTO town VALUES (856,7,'Sant Joan de Labritja');
INSERT INTO town VALUES (857,7,'Sant Josep de sa Talaia');
INSERT INTO town VALUES (858,7,'Sant Llorenç des Cardassar');
INSERT INTO town VALUES (859,7,'Sant Lluís');
INSERT INTO town VALUES (860,7,'Santa Eugènia');
INSERT INTO town VALUES (861,7,'Santa Eulalia del Río');
INSERT INTO town VALUES (862,7,'Santa Margalida');
INSERT INTO town VALUES (863,7,'Santa María del Camí');
INSERT INTO town VALUES (864,7,'Santanyí');
INSERT INTO town VALUES (865,7,'Selva');
INSERT INTO town VALUES (866,7,'Sencelles');
INSERT INTO town VALUES (867,7,'Sineu');
INSERT INTO town VALUES (868,7,'Sóller');
INSERT INTO town VALUES (869,7,'Son Servera');
INSERT INTO town VALUES (870,7,'Valldemossa');
INSERT INTO town VALUES (871,7,'Vilafranca de Bonany');
INSERT INTO town VALUES (872,8,'Abrera');
INSERT INTO town VALUES (873,8,'Aguilar de Segarra');
INSERT INTO town VALUES (874,8,'Aiguafreda');
INSERT INTO town VALUES (875,8,'Alella');
INSERT INTO town VALUES (876,8,'Alpens');
INSERT INTO town VALUES (877,8,'Ametlla del Vallès ');
INSERT INTO town VALUES (878,8,'Arenys de Mar');
INSERT INTO town VALUES (879,8,'Arenys de Munt');
INSERT INTO town VALUES (880,8,'Argençola');
INSERT INTO town VALUES (881,8,'Argentona');
INSERT INTO town VALUES (882,8,'Artés');
INSERT INTO town VALUES (883,8,'Avià');
INSERT INTO town VALUES (884,8,'Avinyó');
INSERT INTO town VALUES (885,8,'Avinyonet del Penedès');
INSERT INTO town VALUES (886,8,'Badalona');
INSERT INTO town VALUES (887,8,'Badia del Vallès');
INSERT INTO town VALUES (888,8,'Bagà');
INSERT INTO town VALUES (889,8,'Balenyà');
INSERT INTO town VALUES (890,8,'Balsareny');
INSERT INTO town VALUES (891,8,'Barberà del Vallès');
INSERT INTO town VALUES (892,8,'Barcelona');
INSERT INTO town VALUES (893,8,'Begues');
INSERT INTO town VALUES (894,8,'Bellprat');
INSERT INTO town VALUES (895,8,'Berga');
INSERT INTO town VALUES (896,8,'Bigues i Riells');
INSERT INTO town VALUES (897,8,'Borredà');
INSERT INTO town VALUES (898,8,'Bruc (El)');
INSERT INTO town VALUES (899,8,'Brull (El)');
INSERT INTO town VALUES (900,8,'Cabanyes (Les)');
INSERT INTO town VALUES (901,8,'Cabrera de Mar');
INSERT INTO town VALUES (902,8,'Cabrera deIgualada');
INSERT INTO town VALUES (903,8,'Cabrils');
INSERT INTO town VALUES (904,8,'Calaf');
INSERT INTO town VALUES (905,8,'Calders');
INSERT INTO town VALUES (906,8,'Caldes de Montbui');
INSERT INTO town VALUES (907,8,'Caldes deEstrac');
INSERT INTO town VALUES (908,8,'Calella');
INSERT INTO town VALUES (909,8,'Calldetenes');
INSERT INTO town VALUES (910,8,'Callús');
INSERT INTO town VALUES (911,8,'Calonge de Segarra');
INSERT INTO town VALUES (912,8,'Campins');
INSERT INTO town VALUES (913,8,'Canet de Mar');
INSERT INTO town VALUES (914,8,'Canovelles');
INSERT INTO town VALUES (915,8,'Cànoves i Samalús');
INSERT INTO town VALUES (916,8,'Canyelles');
INSERT INTO town VALUES (917,8,'Capellades');
INSERT INTO town VALUES (918,8,'Capolat');
INSERT INTO town VALUES (919,8,'Cardedeu');
INSERT INTO town VALUES (920,8,'Cardona');
INSERT INTO town VALUES (921,8,'Carme');
INSERT INTO town VALUES (922,8,'Casserres');
INSERT INTO town VALUES (923,8,'Castell de lAreny');
INSERT INTO town VALUES (924,8,'Castellar de nHug');
INSERT INTO town VALUES (925,8,'Castellar del Riu');
INSERT INTO town VALUES (926,8,'Castellar del Vallès');
INSERT INTO town VALUES (927,8,'Castellbell i el Vilar');
INSERT INTO town VALUES (928,8,'Castellbisbal');
INSERT INTO town VALUES (929,8,'Castellcir');
INSERT INTO town VALUES (930,8,'Castelldefels');
INSERT INTO town VALUES (931,8,'Castellet i la Gornal');
INSERT INTO town VALUES (932,8,'Castellfollit de Riubregós');
INSERT INTO town VALUES (933,8,'Castellfollit del Boix');
INSERT INTO town VALUES (934,8,'Castellgalí');
INSERT INTO town VALUES (935,8,'Castellnou de Bages');
INSERT INTO town VALUES (936,8,'Castellolí');
INSERT INTO town VALUES (937,8,'Castellterçol');
INSERT INTO town VALUES (938,8,'Castellví de la Marca');
INSERT INTO town VALUES (939,8,'Castellví de Rosanes');
INSERT INTO town VALUES (940,8,'Centelles');
INSERT INTO town VALUES (941,8,'Cercs');
INSERT INTO town VALUES (942,8,'Cerdanyola del Vallès');
INSERT INTO town VALUES (943,8,'Cervelló');
INSERT INTO town VALUES (944,8,'Collbató');
INSERT INTO town VALUES (945,8,'Collsuspina');
INSERT INTO town VALUES (946,8,'Copons');
INSERT INTO town VALUES (947,8,'Corbera de Llobregat');
INSERT INTO town VALUES (948,8,'Cornellà de Llobregat');
INSERT INTO town VALUES (949,8,'Cubelles');
INSERT INTO town VALUES (950,8,'Dosrius');
INSERT INTO town VALUES (951,8,'Esparreguera');
INSERT INTO town VALUES (952,8,'Esplugues de Llobregat');
INSERT INTO town VALUES (953,8,'Espunyola ');
INSERT INTO town VALUES (954,8,'Estany ');
INSERT INTO town VALUES (955,8,'Figaró-Montmany');
INSERT INTO town VALUES (956,8,'Fígols');
INSERT INTO town VALUES (957,8,'Fogars de la Selva');
INSERT INTO town VALUES (958,8,'Fogars de Montclús');
INSERT INTO town VALUES (959,8,'Folgueroles');
INSERT INTO town VALUES (960,8,'Fonollosa');
INSERT INTO town VALUES (961,8,'Font-rubí');
INSERT INTO town VALUES (962,8,'Franqueses del Vallès (Les)');
INSERT INTO town VALUES (963,8,'Gaià');
INSERT INTO town VALUES (964,8,'Gallifa');
INSERT INTO town VALUES (965,8,'Garriga (La)');
INSERT INTO town VALUES (966,8,'Gavà');
INSERT INTO town VALUES (967,8,'Gelida');
INSERT INTO town VALUES (968,8,'Gironella');
INSERT INTO town VALUES (969,8,'Gisclareny');
INSERT INTO town VALUES (970,8,'Granada (La)');
INSERT INTO town VALUES (971,8,'Granera');
INSERT INTO town VALUES (972,8,'Granollers');
INSERT INTO town VALUES (973,8,'Gualba');
INSERT INTO town VALUES (974,8,'Guardiola de Berguedà');
INSERT INTO town VALUES (975,8,'Gurb');
INSERT INTO town VALUES (976,8,'Hospitalet de Llobregat ');
INSERT INTO town VALUES (977,8,'Hostalets de Pierola (Els)');
INSERT INTO town VALUES (978,8,'Igualada');
INSERT INTO town VALUES (979,8,'Jorba');
INSERT INTO town VALUES (980,8,'Llacuna (La)');
INSERT INTO town VALUES (981,8,'Llagosta (La)');
INSERT INTO town VALUES (982,8,'Lliçà deAmunt');
INSERT INTO town VALUES (983,8,'Lliçà de Vall');
INSERT INTO town VALUES (984,8,'Llinars del Vallès');
INSERT INTO town VALUES (985,8,'Lluçà');
INSERT INTO town VALUES (986,8,'Malgrat de Mar');
INSERT INTO town VALUES (987,8,'Malla');
INSERT INTO town VALUES (988,8,'Manlleu');
INSERT INTO town VALUES (989,8,'Manresa');
INSERT INTO town VALUES (990,8,'Marganell');
INSERT INTO town VALUES (991,8,'Martorell');
INSERT INTO town VALUES (992,8,'Martorelles');
INSERT INTO town VALUES (993,8,'Masies de Roda (Les)');
INSERT INTO town VALUES (994,8,'Masies de Voltregà (Les)');
INSERT INTO town VALUES (995,8,'Masnou (El)');
INSERT INTO town VALUES (996,8,'Masquefa');
INSERT INTO town VALUES (997,8,'Matadepera');
INSERT INTO town VALUES (998,8,'Mataró');
INSERT INTO town VALUES (999,8,'Mediona');
INSERT INTO town VALUES (1000,8,'Moià');
INSERT INTO town VALUES (1001,8,'Molins de Rei');
INSERT INTO town VALUES (1002,8,'Mollet del Vallès');
INSERT INTO town VALUES (1003,8,'Monistrol de Calders');
INSERT INTO town VALUES (1004,8,'Monistrol de Montserrat');
INSERT INTO town VALUES (1005,8,'Montcada i Reixac');
INSERT INTO town VALUES (1006,8,'Montclar');
INSERT INTO town VALUES (1007,8,'Montesquiu');
INSERT INTO town VALUES (1008,8,'Montgat');
INSERT INTO town VALUES (1009,8,'Montmajor');
INSERT INTO town VALUES (1010,8,'Montmaneu');
INSERT INTO town VALUES (1011,8,'Montmeló');
INSERT INTO town VALUES (1012,8,'Montornès del Vallès');
INSERT INTO town VALUES (1013,8,'Montseny');
INSERT INTO town VALUES (1014,8,'Muntanyola');
INSERT INTO town VALUES (1015,8,'Mura');
INSERT INTO town VALUES (1016,8,'Navarcles');
INSERT INTO town VALUES (1017,8,'Navàs');
INSERT INTO town VALUES (1018,8,'Nou de Berguedà (La)');
INSERT INTO town VALUES (1019,8,'Òdena');
INSERT INTO town VALUES (1020,8,'Olèrdola');
INSERT INTO town VALUES (1021,8,'Olesa de Bonesvalls');
INSERT INTO town VALUES (1022,8,'Olesa de Montserrat');
INSERT INTO town VALUES (1023,8,'Olivella');
INSERT INTO town VALUES (1024,8,'Olost');
INSERT INTO town VALUES (1025,8,'Olvan');
INSERT INTO town VALUES (1026,8,'Orís');
INSERT INTO town VALUES (1027,8,'Oristà');
INSERT INTO town VALUES (1028,8,'Orpí');
INSERT INTO town VALUES (1029,8,'Òrrius');
INSERT INTO town VALUES (1030,8,'Pacs del Penedès');
INSERT INTO town VALUES (1031,8,'Palafolls');
INSERT INTO town VALUES (1032,8,'Palau-solità i Plegamans');
INSERT INTO town VALUES (1033,8,'Pallejà');
INSERT INTO town VALUES (1034,8,'Palma de Cervelló (La)');
INSERT INTO town VALUES (1035,8,'Papiol (El)');
INSERT INTO town VALUES (1036,8,'Parets del Vallès');
INSERT INTO town VALUES (1037,8,'Perafita');
INSERT INTO town VALUES (1038,8,'Piera');
INSERT INTO town VALUES (1039,8,'Pineda de Mar');
INSERT INTO town VALUES (1040,8,'Pla del Penedès (El)');
INSERT INTO town VALUES (1041,8,'Pobla de Claramunt (La)');
INSERT INTO town VALUES (1042,8,'Pobla de Lillet (La)');
INSERT INTO town VALUES (1043,8,'Polinyà');
INSERT INTO town VALUES (1044,8,'Pont de Vilomara i Rocafort (El)');
INSERT INTO town VALUES (1045,8,'Pontons');
INSERT INTO town VALUES (1046,8,'Prat de Llobregat (El)');
INSERT INTO town VALUES (1047,8,'Prats de Lluçanès');
INSERT INTO town VALUES (1048,8,'Prats de Rei (Els)');
INSERT INTO town VALUES (1049,8,'Premià de Dalt');
INSERT INTO town VALUES (1050,8,'Premià de Mar');
INSERT INTO town VALUES (1051,8,'Puigdàlber');
INSERT INTO town VALUES (1052,8,'Puig-reig');
INSERT INTO town VALUES (1053,8,'Pujalt');
INSERT INTO town VALUES (1054,8,'Quar (La)');
INSERT INTO town VALUES (1055,8,'Rajadell');
INSERT INTO town VALUES (1056,8,'Rellinars');
INSERT INTO town VALUES (1057,8,'Ripollet');
INSERT INTO town VALUES (1058,8,'Roca del Vallès (La)');
INSERT INTO town VALUES (1059,8,'Roda de Ter');
INSERT INTO town VALUES (1060,8,'Rubí');
INSERT INTO town VALUES (1061,8,'Rubió');
INSERT INTO town VALUES (1062,8,'Rupit i Pruit');
INSERT INTO town VALUES (1063,8,'Sabadell');
INSERT INTO town VALUES (1064,8,'Sagàs');
INSERT INTO town VALUES (1065,8,'Saldes');
INSERT INTO town VALUES (1066,8,'Sallent');
INSERT INTO town VALUES (1067,8,'Sant Adrià de Besòs');
INSERT INTO town VALUES (1068,8,'Sant Agustí de Lluçanès');
INSERT INTO town VALUES (1069,8,'Sant Andreu de la Barca');
INSERT INTO town VALUES (1070,8,'Sant Andreu de Llavaneres');
INSERT INTO town VALUES (1071,8,'Sant Antoni de Vilamajor');
INSERT INTO town VALUES (1072,8,'Sant Bartomeu del Grau');
INSERT INTO town VALUES (1073,8,'Sant Boi de Llobregat');
INSERT INTO town VALUES (1074,8,'Sant Boi de Lluçanès');
INSERT INTO town VALUES (1075,8,'Sant Cebrià de Vallalta');
INSERT INTO town VALUES (1076,8,'Sant Celoni');
INSERT INTO town VALUES (1077,8,'Sant Climent de Llobregat');
INSERT INTO town VALUES (1078,8,'Sant Cugat del Vallès');
INSERT INTO town VALUES (1079,8,'Sant Cugat Sesgarrigues');
INSERT INTO town VALUES (1080,8,'Sant Esteve de Palautordera');
INSERT INTO town VALUES (1081,8,'Sant Esteve Sesrovires');
INSERT INTO town VALUES (1082,8,'Sant Feliu de Codines');
INSERT INTO town VALUES (1083,8,'Sant Feliu de Llobregat');
INSERT INTO town VALUES (1084,8,'Sant Feliu Sasserra');
INSERT INTO town VALUES (1085,8,'Sant Fost de Campsentelles');
INSERT INTO town VALUES (1086,8,'Sant Fruitós de Bages');
INSERT INTO town VALUES (1087,8,'Sant Hipòlit de Voltregà');
INSERT INTO town VALUES (1088,8,'Sant Iscle de Vallalta');
INSERT INTO town VALUES (1089,8,'Sant Jaume de Frontanyà');
INSERT INTO town VALUES (1090,8,'Sant Joan de Vilatorrada');
INSERT INTO town VALUES (1091,8,'Sant Joan Despí');
INSERT INTO town VALUES (1092,8,'Sant Julià de Cerdanyola');
INSERT INTO town VALUES (1093,8,'Sant Julià de Vilatorta');
INSERT INTO town VALUES (1094,8,'Sant Just Desvern');
INSERT INTO town VALUES (1095,8,'Sant Llorenç deHortons');
INSERT INTO town VALUES (1096,8,'Sant Llorenç Savall');
INSERT INTO town VALUES (1097,8,'Sant Martí deAlbars');
INSERT INTO town VALUES (1098,8,'Sant Martí de Centelles');
INSERT INTO town VALUES (1099,8,'Sant Martí de Tous');
INSERT INTO town VALUES (1100,8,'Sant Martí Sarroca');
INSERT INTO town VALUES (1101,8,'Sant Martí Sesgueioles');
INSERT INTO town VALUES (1102,8,'Sant Mateu de Bages');
INSERT INTO town VALUES (1103,8,'Sant Pere de Ribes');
INSERT INTO town VALUES (1104,8,'Sant Pere de Riudebitlles');
INSERT INTO town VALUES (1105,8,'Sant Pere de Torelló');
INSERT INTO town VALUES (1106,8,'Sant Pere de Vilamajor');
INSERT INTO town VALUES (1107,8,'Sant Pere Sallavinera');
INSERT INTO town VALUES (1108,8,'Sant Pol de Mar');
INSERT INTO town VALUES (1109,8,'Sant Quintí de Mediona');
INSERT INTO town VALUES (1110,8,'Sant Quirze de Besora');
INSERT INTO town VALUES (1111,8,'Sant Quirze del Vallès');
INSERT INTO town VALUES (1112,8,'Sant Quirze Safaja');
INSERT INTO town VALUES (1113,8,'Sant Sadurní deAnoia');
INSERT INTO town VALUES (1114,8,'Sant Sadurní deOsormort');
INSERT INTO town VALUES (1115,8,'Sant Salvador de Guardiola');
INSERT INTO town VALUES (1116,8,'Sant Vicenç de Castellet');
INSERT INTO town VALUES (1117,8,'Sant Vicenç de Montalt');
INSERT INTO town VALUES (1118,8,'Sant Vicenç de Torelló');
INSERT INTO town VALUES (1119,8,'Sant Vicenç dels Horts');
INSERT INTO town VALUES (1120,8,'Santa Cecília de Voltregà');
INSERT INTO town VALUES (1121,8,'Santa Coloma de Cervelló');
INSERT INTO town VALUES (1122,8,'Santa Coloma de Gramenet');
INSERT INTO town VALUES (1123,8,'Santa Eugènia de Berga');
INSERT INTO town VALUES (1124,8,'Santa Eulàlia de Riuprimer');
INSERT INTO town VALUES (1125,8,'Santa Eulàlia de Ronçana');
INSERT INTO town VALUES (1126,8,'Santa Fe del Penedès');
INSERT INTO town VALUES (1127,8,'Santa Margarida de Montbui');
INSERT INTO town VALUES (1128,8,'Santa Margarida i els Monjos');
INSERT INTO town VALUES (1129,8,'Santa Maria de Besora');
INSERT INTO town VALUES (1130,8,'Santa Maria de Corcó');
INSERT INTO town VALUES (1131,8,'Santa Maria de Martorelles');
INSERT INTO town VALUES (1132,8,'Santa Maria de Merlès');
INSERT INTO town VALUES (1133,8,'Santa Maria de Miralles');
INSERT INTO town VALUES (1134,8,'Santa Maria de Palautordera');
INSERT INTO town VALUES (1135,8,'Santa Maria deOló');
INSERT INTO town VALUES (1136,8,'Santa Perpètua de Mogoda');
INSERT INTO town VALUES (1137,8,'Santa Susanna');
INSERT INTO town VALUES (1138,8,'Santpedor');
INSERT INTO town VALUES (1139,8,'Sentmenat');
INSERT INTO town VALUES (1140,8,'Seva');
INSERT INTO town VALUES (1141,8,'Sitges');
INSERT INTO town VALUES (1142,8,'Sobremunt');
INSERT INTO town VALUES (1143,8,'Sora');
INSERT INTO town VALUES (1144,8,'Subirats');
INSERT INTO town VALUES (1145,8,'Súria');
INSERT INTO town VALUES (1146,8,'Tagamanent');
INSERT INTO town VALUES (1147,8,'Talamanca');
INSERT INTO town VALUES (1148,8,'Taradell');
INSERT INTO town VALUES (1149,8,'Tavèrnoles');
INSERT INTO town VALUES (1150,8,'Tavertet');
INSERT INTO town VALUES (1151,8,'Teià');
INSERT INTO town VALUES (1152,8,'Terrassa');
INSERT INTO town VALUES (1153,8,'Tiana');
INSERT INTO town VALUES (1154,8,'Tona');
INSERT INTO town VALUES (1155,8,'Tordera');
INSERT INTO town VALUES (1156,8,'Torelló');
INSERT INTO town VALUES (1157,8,'Torre de Claramunt (La)');
INSERT INTO town VALUES (1158,8,'Torrelavit');
INSERT INTO town VALUES (1159,8,'Torrelles de Foix');
INSERT INTO town VALUES (1160,8,'Torrelles de Llobregat');
INSERT INTO town VALUES (1161,8,'Ullastrell');
INSERT INTO town VALUES (1162,8,'Vacarisses');
INSERT INTO town VALUES (1163,8,'Vallbona deAnoia');
INSERT INTO town VALUES (1164,8,'Vallcebre');
INSERT INTO town VALUES (1165,8,'Vallgorguina');
INSERT INTO town VALUES (1166,8,'Vallirana');
INSERT INTO town VALUES (1167,8,'Vallromanes');
INSERT INTO town VALUES (1168,8,'Veciana');
INSERT INTO town VALUES (1169,8,'Vic');
INSERT INTO town VALUES (1170,8,'Vilada');
INSERT INTO town VALUES (1171,8,'Viladecans');
INSERT INTO town VALUES (1172,8,'Viladecavalls');
INSERT INTO town VALUES (1173,8,'Vilafranca del Penedès');
INSERT INTO town VALUES (1174,8,'Vilalba Sasserra');
INSERT INTO town VALUES (1175,8,'Vilanova de Sau');
INSERT INTO town VALUES (1176,8,'Vilanova del Camí');
INSERT INTO town VALUES (1177,8,'Vilanova del Vallès');
INSERT INTO town VALUES (1178,8,'Vilanova i la Geltrú');
INSERT INTO town VALUES (1179,8,'Vilassar de Dalt');
INSERT INTO town VALUES (1180,8,'Vilassar de Mar');
INSERT INTO town VALUES (1181,8,'Vilobí del Penedès');
INSERT INTO town VALUES (1182,8,'Viver i Serrateix');
INSERT INTO town VALUES (1183,9,'Abajas');
INSERT INTO town VALUES (1184,9,'Adrada de Haza');
INSERT INTO town VALUES (1185,9,'Aguas Cándidas');
INSERT INTO town VALUES (1186,9,'Aguilar de Bureba');
INSERT INTO town VALUES (1187,9,'Albillos');
INSERT INTO town VALUES (1188,9,'Alcocero de Mola');
INSERT INTO town VALUES (1189,9,'Alfoz de Bricia');
INSERT INTO town VALUES (1190,9,'Alfoz de Quintanadueñas');
INSERT INTO town VALUES (1191,9,'Alfoz de Santa Gadea');
INSERT INTO town VALUES (1192,9,'Altable');
INSERT INTO town VALUES (1193,9,'Altos (Los)');
INSERT INTO town VALUES (1194,9,'Ameyugo');
INSERT INTO town VALUES (1195,9,'Anguix');
INSERT INTO town VALUES (1196,9,'Aranda de Duero');
INSERT INTO town VALUES (1197,9,'Arandilla');
INSERT INTO town VALUES (1198,9,'Arauzo de Miel');
INSERT INTO town VALUES (1199,9,'Arauzo de Salce');
INSERT INTO town VALUES (1200,9,'Arauzo de Torre');
INSERT INTO town VALUES (1201,9,'Arcos');
INSERT INTO town VALUES (1202,9,'Arenillas de Riopisuerga');
INSERT INTO town VALUES (1203,9,'Arija');
INSERT INTO town VALUES (1204,9,'Arlanzón');
INSERT INTO town VALUES (1205,9,'Arraya de Oca');
INSERT INTO town VALUES (1206,9,'Atapuerca');
INSERT INTO town VALUES (1207,9,'Ausines (Los)');
INSERT INTO town VALUES (1208,9,'Avellanosa de Muñó');
INSERT INTO town VALUES (1209,9,'Bahabón de Esgueva');
INSERT INTO town VALUES (1210,9,'Balbases (Los)');
INSERT INTO town VALUES (1211,9,'Baños de Valdearados');
INSERT INTO town VALUES (1212,9,'Bañuelos de Bureba');
INSERT INTO town VALUES (1213,9,'Barbadillo de Herreros');
INSERT INTO town VALUES (1214,9,'Barbadillo del Mercado');
INSERT INTO town VALUES (1215,9,'Barbadillo del Pez');
INSERT INTO town VALUES (1216,9,'Barrio de Muñó');
INSERT INTO town VALUES (1217,9,'Barrios de Bureba (Los)');
INSERT INTO town VALUES (1218,9,'Barrios de Colina');
INSERT INTO town VALUES (1219,9,'Basconcillos del Tozo');
INSERT INTO town VALUES (1220,9,'Bascuñana');
INSERT INTO town VALUES (1221,9,'Belbimbre');
INSERT INTO town VALUES (1222,9,'Belorado');
INSERT INTO town VALUES (1223,9,'Berberana');
INSERT INTO town VALUES (1224,9,'Berlangas de Roa');
INSERT INTO town VALUES (1225,9,'Berzosa de Bureba');
INSERT INTO town VALUES (1226,9,'Bozoó');
INSERT INTO town VALUES (1227,9,'Brazacorta');
INSERT INTO town VALUES (1228,9,'Briviesca');
INSERT INTO town VALUES (1229,9,'Bugedo');
INSERT INTO town VALUES (1230,9,'Buniel');
INSERT INTO town VALUES (1231,9,'Burgos');
INSERT INTO town VALUES (1232,9,'Busto de Bureba');
INSERT INTO town VALUES (1233,9,'Cabañes de Esgueva');
INSERT INTO town VALUES (1234,9,'Cabezón de la Sierra');
INSERT INTO town VALUES (1235,9,'Caleruega');
INSERT INTO town VALUES (1236,9,'Campillo de Aranda');
INSERT INTO town VALUES (1237,9,'Campolara');
INSERT INTO town VALUES (1238,9,'Canicosa de la Sierra');
INSERT INTO town VALUES (1239,9,'Cantabrana');
INSERT INTO town VALUES (1240,9,'Carazo');
INSERT INTO town VALUES (1241,9,'Carcedo de Bureba');
INSERT INTO town VALUES (1242,9,'Carcedo de Burgos');
INSERT INTO town VALUES (1243,9,'Cardeñadijo');
INSERT INTO town VALUES (1244,9,'Cardeñajimeno');
INSERT INTO town VALUES (1245,9,'Cardeñuela Riopico');
INSERT INTO town VALUES (1246,9,'Carrias');
INSERT INTO town VALUES (1247,9,'Cascajares de Bureba');
INSERT INTO town VALUES (1248,9,'Cascajares de la Sierra');
INSERT INTO town VALUES (1249,9,'Castellanos de Castro');
INSERT INTO town VALUES (1250,9,'Castil de Peones');
INSERT INTO town VALUES (1251,9,'Castildelgado');
INSERT INTO town VALUES (1252,9,'Castrillo de la Reina');
INSERT INTO town VALUES (1253,9,'Castrillo de la Vega');
INSERT INTO town VALUES (1254,9,'Castrillo de Riopisuerga');
INSERT INTO town VALUES (1255,9,'Castrillo del Val');
INSERT INTO town VALUES (1256,9,'Castrillo Matajudíos');
INSERT INTO town VALUES (1257,9,'Castrojeriz');
INSERT INTO town VALUES (1258,9,'Cavia');
INSERT INTO town VALUES (1259,9,'Cayuela');
INSERT INTO town VALUES (1260,9,'Cebrecos');
INSERT INTO town VALUES (1261,9,'Celada del Camino');
INSERT INTO town VALUES (1262,9,'Cerezo de Río Tirón');
INSERT INTO town VALUES (1263,9,'Cerratón de Juarros');
INSERT INTO town VALUES (1264,9,'Ciadoncha');
INSERT INTO town VALUES (1265,9,'Cillaperlata');
INSERT INTO town VALUES (1266,9,'Cilleruelo de Abajo');
INSERT INTO town VALUES (1267,9,'Cilleruelo de Arriba');
INSERT INTO town VALUES (1268,9,'Ciruelos de Cervera');
INSERT INTO town VALUES (1269,9,'Cogollos');
INSERT INTO town VALUES (1270,9,'Condado de Treviño');
INSERT INTO town VALUES (1271,9,'Contreras');
INSERT INTO town VALUES (1272,9,'Coruña del Conde');
INSERT INTO town VALUES (1273,9,'Covarrubias');
INSERT INTO town VALUES (1274,9,'Cubillo del Campo');
INSERT INTO town VALUES (1275,9,'Cubo de Bureba');
INSERT INTO town VALUES (1276,9,'Cueva de Roa (La)');
INSERT INTO town VALUES (1277,9,'Cuevas de San Clemente');
INSERT INTO town VALUES (1278,9,'Encío');
INSERT INTO town VALUES (1279,9,'Espinosa de Cervera');
INSERT INTO town VALUES (1280,9,'Espinosa de los Monteros');
INSERT INTO town VALUES (1281,9,'Espinosa del Camino');
INSERT INTO town VALUES (1282,9,'Estépar');
INSERT INTO town VALUES (1283,9,'Fontioso');
INSERT INTO town VALUES (1284,9,'Frandovínez');
INSERT INTO town VALUES (1285,9,'Fresneda de la Sierra Tirón');
INSERT INTO town VALUES (1286,9,'Fresneña');
INSERT INTO town VALUES (1287,9,'Fresnillo de las Dueñas');
INSERT INTO town VALUES (1288,9,'Fresno de Río Tirón');
INSERT INTO town VALUES (1289,9,'Fresno de Rodilla');
INSERT INTO town VALUES (1290,9,'Frías');
INSERT INTO town VALUES (1291,9,'Fuentebureba');
INSERT INTO town VALUES (1292,9,'Fuentecén');
INSERT INTO town VALUES (1293,9,'Fuentelcésped');
INSERT INTO town VALUES (1294,9,'Fuentelisendo');
INSERT INTO town VALUES (1295,9,'Fuentemolinos');
INSERT INTO town VALUES (1296,9,'Fuentenebro');
INSERT INTO town VALUES (1297,9,'Fuentespina');
INSERT INTO town VALUES (1298,9,'Galbarros');
INSERT INTO town VALUES (1299,9,'Gallega (La)');
INSERT INTO town VALUES (1300,9,'Grijalba');
INSERT INTO town VALUES (1301,9,'Grisaleña');
INSERT INTO town VALUES (1302,9,'Gumiel de Izán');
INSERT INTO town VALUES (1303,9,'Gumiel de Mercado');
INSERT INTO town VALUES (1304,9,'Hacinas');
INSERT INTO town VALUES (1305,9,'Haza');
INSERT INTO town VALUES (1306,9,'Hontanas');
INSERT INTO town VALUES (1307,9,'Hontangas');
INSERT INTO town VALUES (1308,9,'Hontoria de la Cantera');
INSERT INTO town VALUES (1309,9,'Hontoria de Valdearados');
INSERT INTO town VALUES (1310,9,'Hontoria del Pinar');
INSERT INTO town VALUES (1311,9,'Hormazas (Las)');
INSERT INTO town VALUES (1312,9,'Hornillos del Camino');
INSERT INTO town VALUES (1313,9,'Horra (La)');
INSERT INTO town VALUES (1314,9,'Hortigüela');
INSERT INTO town VALUES (1315,9,'Hoyales de Roa');
INSERT INTO town VALUES (1316,9,'Huérmeces');
INSERT INTO town VALUES (1317,9,'Huerta de Arriba');
INSERT INTO town VALUES (1318,9,'Huerta de Rey');
INSERT INTO town VALUES (1319,9,'Humada');
INSERT INTO town VALUES (1320,9,'Hurones');
INSERT INTO town VALUES (1321,9,'Ibeas de Juarros');
INSERT INTO town VALUES (1322,9,'Ibrillos');
INSERT INTO town VALUES (1323,9,'Iglesiarrubia');
INSERT INTO town VALUES (1324,9,'Iglesias');
INSERT INTO town VALUES (1325,9,'Isar');
INSERT INTO town VALUES (1326,9,'Itero del Castillo');
INSERT INTO town VALUES (1327,9,'Jaramillo de la Fuente');
INSERT INTO town VALUES (1328,9,'Jaramillo Quemado');
INSERT INTO town VALUES (1329,9,'Junta de Traslaloma');
INSERT INTO town VALUES (1330,9,'Junta de Villalba de Losa');
INSERT INTO town VALUES (1331,9,'Jurisdicción de Lara');
INSERT INTO town VALUES (1332,9,'Jurisdicción de San Zadornil');
INSERT INTO town VALUES (1333,9,'Lerma');
INSERT INTO town VALUES (1334,9,'Llano de Bureba');
INSERT INTO town VALUES (1335,9,'Madrigal del Monte');
INSERT INTO town VALUES (1336,9,'Madrigalejo del Monte');
INSERT INTO town VALUES (1337,9,'Mahamud');
INSERT INTO town VALUES (1338,9,'Mambrilla de Castrejón');
INSERT INTO town VALUES (1339,9,'Mambrillas de Lara');
INSERT INTO town VALUES (1340,9,'Mamolar');
INSERT INTO town VALUES (1341,9,'Manciles');
INSERT INTO town VALUES (1342,9,'Mazuela');
INSERT INTO town VALUES (1343,9,'Mecerreyes');
INSERT INTO town VALUES (1344,9,'Medina de Pomar');
INSERT INTO town VALUES (1345,9,'Melgar de Fernamental');
INSERT INTO town VALUES (1346,9,'Merindad de Cuesta-Urria');
INSERT INTO town VALUES (1347,9,'Merindad de Montija');
INSERT INTO town VALUES (1348,9,'Merindad de Río Ubierna');
INSERT INTO town VALUES (1349,9,'Merindad de Sotoscueva');
INSERT INTO town VALUES (1350,9,'Merindad de Valdeporres');
INSERT INTO town VALUES (1351,9,'Merindad de Valdivielso');
INSERT INTO town VALUES (1352,9,'Milagros');
INSERT INTO town VALUES (1353,9,'Miranda de Ebro');
INSERT INTO town VALUES (1354,9,'Miraveche');
INSERT INTO town VALUES (1355,9,'Modúbar de la Emparedada');
INSERT INTO town VALUES (1356,9,'Monasterio de la Sierra');
INSERT INTO town VALUES (1357,9,'Monasterio de Rodilla');
INSERT INTO town VALUES (1358,9,'Moncalvillo');
INSERT INTO town VALUES (1359,9,'Monterrubio de la Demanda');
INSERT INTO town VALUES (1360,9,'Montorio');
INSERT INTO town VALUES (1361,9,'Moradillo de Roa');
INSERT INTO town VALUES (1362,9,'Nava de Roa');
INSERT INTO town VALUES (1363,9,'Navas de Bureba');
INSERT INTO town VALUES (1364,9,'Nebreda');
INSERT INTO town VALUES (1365,9,'Neila');
INSERT INTO town VALUES (1366,9,'Olmedillo de Roa');
INSERT INTO town VALUES (1367,9,'Olmillos de Muñó');
INSERT INTO town VALUES (1368,9,'Oña');
INSERT INTO town VALUES (1369,9,'Oquillas');
INSERT INTO town VALUES (1370,9,'Orbaneja Riopico');
INSERT INTO town VALUES (1371,9,'Padilla de Abajo');
INSERT INTO town VALUES (1372,9,'Padilla de Arriba');
INSERT INTO town VALUES (1373,9,'Padrones de Bureba');
INSERT INTO town VALUES (1374,9,'Palacios de la Sierra');
INSERT INTO town VALUES (1375,9,'Palacios de Riopisuerga');
INSERT INTO town VALUES (1376,9,'Palazuelos de la Sierra');
INSERT INTO town VALUES (1377,9,'Palazuelos de Muñó');
INSERT INTO town VALUES (1378,9,'Pampliega');
INSERT INTO town VALUES (1379,9,'Pancorbo');
INSERT INTO town VALUES (1380,9,'Pardilla');
INSERT INTO town VALUES (1381,9,'Partido de la Sierra en Tobalina');
INSERT INTO town VALUES (1382,9,'Pedrosa de Duero');
INSERT INTO town VALUES (1383,9,'Pedrosa de Río Úrbel');
INSERT INTO town VALUES (1384,9,'Pedrosa del Páramo');
INSERT INTO town VALUES (1385,9,'Pedrosa del Príncipe');
INSERT INTO town VALUES (1386,9,'Peñaranda de Duero');
INSERT INTO town VALUES (1387,9,'Peral de Arlanza');
INSERT INTO town VALUES (1388,9,'Piérnigas');
INSERT INTO town VALUES (1389,9,'Pineda de la Sierra');
INSERT INTO town VALUES (1390,9,'Pineda Trasmonte');
INSERT INTO town VALUES (1391,9,'Pinilla de los Barruecos');
INSERT INTO town VALUES (1392,9,'Pinilla de los Moros');
INSERT INTO town VALUES (1393,9,'Pinilla Trasmonte');
INSERT INTO town VALUES (1394,9,'Poza de la Sal');
INSERT INTO town VALUES (1395,9,'Prádanos de Bureba');
INSERT INTO town VALUES (1396,9,'Pradoluengo');
INSERT INTO town VALUES (1397,9,'Presencio');
INSERT INTO town VALUES (1398,9,'Puebla de Arganzón (La)');
INSERT INTO town VALUES (1399,9,'Puentedura');
INSERT INTO town VALUES (1400,9,'Quemada');
INSERT INTO town VALUES (1401,9,'Quintana del Pidio');
INSERT INTO town VALUES (1402,9,'Quintanabureba');
INSERT INTO town VALUES (1403,9,'Quintanaélez');
INSERT INTO town VALUES (1404,9,'Quintanaortuño');
INSERT INTO town VALUES (1405,9,'Quintanapalla');
INSERT INTO town VALUES (1406,9,'Quintanar de la Sierra');
INSERT INTO town VALUES (1407,9,'Quintanavides');
INSERT INTO town VALUES (1408,9,'Quintanilla de la Mata');
INSERT INTO town VALUES (1409,9,'Quintanilla del Agua y Tordueles');
INSERT INTO town VALUES (1410,9,'Quintanilla del Coco');
INSERT INTO town VALUES (1411,9,'Quintanilla San García');
INSERT INTO town VALUES (1412,9,'Quintanilla Vivar');
INSERT INTO town VALUES (1413,9,'Quintanillas (Las)');
INSERT INTO town VALUES (1414,9,'Rabanera del Pinar');
INSERT INTO town VALUES (1415,9,'Rábanos');
INSERT INTO town VALUES (1416,9,'Rabé de las Calzadas');
INSERT INTO town VALUES (1417,9,'Rebolledo de la Torre');
INSERT INTO town VALUES (1418,9,'Redecilla del Camino');
INSERT INTO town VALUES (1419,9,'Redecilla del Campo');
INSERT INTO town VALUES (1420,9,'Regumiel de la Sierra');
INSERT INTO town VALUES (1421,9,'Reinoso');
INSERT INTO town VALUES (1422,9,'Retuerta');
INSERT INTO town VALUES (1423,9,'Revilla del Campo');
INSERT INTO town VALUES (1424,9,'Revilla Vallejera');
INSERT INTO town VALUES (1425,9,'Revilla y Ahedo (La)');
INSERT INTO town VALUES (1426,9,'Revillarruz');
INSERT INTO town VALUES (1427,9,'Rezmondo');
INSERT INTO town VALUES (1428,9,'Riocavado de la Sierra');
INSERT INTO town VALUES (1429,9,'Roa');
INSERT INTO town VALUES (1430,9,'Rojas');
INSERT INTO town VALUES (1431,9,'Royuela de Río Franco');
INSERT INTO town VALUES (1432,9,'Rubena');
INSERT INTO town VALUES (1433,9,'Rublacedo de Abajo');
INSERT INTO town VALUES (1434,9,'Rucandio');
INSERT INTO town VALUES (1435,9,'Salas de Bureba');
INSERT INTO town VALUES (1436,9,'Salas de los Infantes');
INSERT INTO town VALUES (1437,9,'Saldaña de Burgos');
INSERT INTO town VALUES (1438,9,'Salinillas de Bureba');
INSERT INTO town VALUES (1439,9,'San Adrián de Juarros');
INSERT INTO town VALUES (1440,9,'San Juan del Monte');
INSERT INTO town VALUES (1441,9,'San Mamés de Burgos');
INSERT INTO town VALUES (1442,9,'San Martín de Rubiales');
INSERT INTO town VALUES (1443,9,'San Millán de Lara');
INSERT INTO town VALUES (1444,9,'San Vicente del Valle');
INSERT INTO town VALUES (1445,9,'Santa Cecilia');
INSERT INTO town VALUES (1446,9,'Santa Cruz de la Salceda');
INSERT INTO town VALUES (1447,9,'Santa Cruz del Valle Urbión');
INSERT INTO town VALUES (1448,9,'Santa Gadea del Cid');
INSERT INTO town VALUES (1449,9,'Santa Inés');
INSERT INTO town VALUES (1450,9,'Santa María del Campo');
INSERT INTO town VALUES (1451,9,'Santa María del Invierno');
INSERT INTO town VALUES (1452,9,'Santa María del Mercadillo');
INSERT INTO town VALUES (1453,9,'Santa María Rivarredonda');
INSERT INTO town VALUES (1454,9,'Santa Olalla de Bureba');
INSERT INTO town VALUES (1455,9,'Santibáñez de Esgueva');
INSERT INTO town VALUES (1456,9,'Santibáñez del Val');
INSERT INTO town VALUES (1457,9,'Santo Domingo de Silos');
INSERT INTO town VALUES (1458,9,'Sargentes de la Lora');
INSERT INTO town VALUES (1459,9,'Sarracín');
INSERT INTO town VALUES (1460,9,'Sasamón');
INSERT INTO town VALUES (1461,9,'Sequera de Haza (La)');
INSERT INTO town VALUES (1462,9,'Solarana');
INSERT INTO town VALUES (1463,9,'Sordillos');
INSERT INTO town VALUES (1464,9,'Sotillo de la Ribera');
INSERT INTO town VALUES (1465,9,'Sotragero');
INSERT INTO town VALUES (1466,9,'Sotresgudo');
INSERT INTO town VALUES (1467,9,'Susinos del Páramo');
INSERT INTO town VALUES (1468,9,'Tamarón');
INSERT INTO town VALUES (1469,9,'Tardajos');
INSERT INTO town VALUES (1470,9,'Tejada');
INSERT INTO town VALUES (1471,9,'Terradillos de Esgueva');
INSERT INTO town VALUES (1472,9,'Tinieblas de la Sierra');
INSERT INTO town VALUES (1473,9,'Tobar');
INSERT INTO town VALUES (1474,9,'Tordómar');
INSERT INTO town VALUES (1475,9,'Torrecilla del Monte');
INSERT INTO town VALUES (1476,9,'Torregalindo');
INSERT INTO town VALUES (1477,9,'Torrelara');
INSERT INTO town VALUES (1478,9,'Torrepadre');
INSERT INTO town VALUES (1479,9,'Torresandino');
INSERT INTO town VALUES (1480,9,'Tórtoles de Esgueva');
INSERT INTO town VALUES (1481,9,'Tosantos');
INSERT INTO town VALUES (1482,9,'Trespaderne');
INSERT INTO town VALUES (1483,9,'Tubilla del Agua');
INSERT INTO town VALUES (1484,9,'Tubilla del Lago');
INSERT INTO town VALUES (1485,9,'Úrbel del Castillo');
INSERT INTO town VALUES (1486,9,'Vadocondes');
INSERT INTO town VALUES (1487,9,'Valdeande');
INSERT INTO town VALUES (1488,9,'Valdezate');
INSERT INTO town VALUES (1489,9,'Valdorros');
INSERT INTO town VALUES (1490,9,'Vallarta de Bureba');
INSERT INTO town VALUES (1491,9,'Valle de las Navas');
INSERT INTO town VALUES (1492,9,'Valle de Losa');
INSERT INTO town VALUES (1493,9,'Valle de Manzanedo');
INSERT INTO town VALUES (1494,9,'Valle de Mena');
INSERT INTO town VALUES (1495,9,'Valle de Oca');
INSERT INTO town VALUES (1496,9,'Valle de Santibáñez');
INSERT INTO town VALUES (1497,9,'Valle de Sedano');
INSERT INTO town VALUES (1498,9,'Valle de Tobalina');
INSERT INTO town VALUES (1499,9,'Valle de Valdebezana');
INSERT INTO town VALUES (1500,9,'Valle de Valdelaguna');
INSERT INTO town VALUES (1501,9,'Valle de Valdelucio');
INSERT INTO town VALUES (1502,9,'Valle de Zamanzas');
INSERT INTO town VALUES (1503,9,'Vallejera');
INSERT INTO town VALUES (1504,9,'Valles de Palenzuela');
INSERT INTO town VALUES (1505,9,'Valluércanes');
INSERT INTO town VALUES (1506,9,'Valmala');
INSERT INTO town VALUES (1507,9,'Vid de Bureba (La)');
INSERT INTO town VALUES (1508,9,'Vid y Barrios (La)');
INSERT INTO town VALUES (1509,9,'Vileña');
INSERT INTO town VALUES (1510,9,'Villadiego');
INSERT INTO town VALUES (1511,9,'Villaescusa de Roa');
INSERT INTO town VALUES (1512,9,'Villaescusa la Sombría');
INSERT INTO town VALUES (1513,9,'Villaespasa');
INSERT INTO town VALUES (1514,9,'Villafranca Montes de Oca');
INSERT INTO town VALUES (1515,9,'Villafruela');
INSERT INTO town VALUES (1516,9,'Villagalijo');
INSERT INTO town VALUES (1517,9,'Villagonzalo Pedernales');
INSERT INTO town VALUES (1518,9,'Villahoz');
INSERT INTO town VALUES (1519,9,'Villalba de Duero');
INSERT INTO town VALUES (1520,9,'Villalbilla de Burgos');
INSERT INTO town VALUES (1521,9,'Villalbilla de Gumiel');
INSERT INTO town VALUES (1522,9,'Villaldemiro');
INSERT INTO town VALUES (1523,9,'Villalmanzo');
INSERT INTO town VALUES (1524,9,'Villamayor de los Montes');
INSERT INTO town VALUES (1525,9,'Villamayor de Treviño');
INSERT INTO town VALUES (1526,9,'Villambistia');
INSERT INTO town VALUES (1527,9,'Villamedianilla');
INSERT INTO town VALUES (1528,9,'Villamiel de la Sierra');
INSERT INTO town VALUES (1529,9,'Villangómez');
INSERT INTO town VALUES (1530,9,'Villanueva de Argaño');
INSERT INTO town VALUES (1531,9,'Villanueva de Carazo');
INSERT INTO town VALUES (1532,9,'Villanueva de Gumiel');
INSERT INTO town VALUES (1533,9,'Villanueva de Teba');
INSERT INTO town VALUES (1534,9,'Villaquirán de la Puebla');
INSERT INTO town VALUES (1535,9,'Villaquirán de los Infantes');
INSERT INTO town VALUES (1536,9,'Villarcayo de Merindad de Castilla la Vieja');
INSERT INTO town VALUES (1537,9,'Villariezo');
INSERT INTO town VALUES (1538,9,'Villasandino');
INSERT INTO town VALUES (1539,9,'Villasur de Herreros');
INSERT INTO town VALUES (1540,9,'Villatuelda');
INSERT INTO town VALUES (1541,9,'Villaverde del Monte');
INSERT INTO town VALUES (1542,9,'Villaverde-Mogina');
INSERT INTO town VALUES (1543,9,'Villayerno Morquillas');
INSERT INTO town VALUES (1544,9,'Villazopeque');
INSERT INTO town VALUES (1545,9,'Villegas');
INSERT INTO town VALUES (1546,9,'Villoruebo');
INSERT INTO town VALUES (1547,9,'Viloria de Rioja');
INSERT INTO town VALUES (1548,9,'Vilviestre del Pinar');
INSERT INTO town VALUES (1549,9,'Vizcaínos');
INSERT INTO town VALUES (1550,9,'Zael');
INSERT INTO town VALUES (1551,9,'Zarzosa de Río Pisuerga');
INSERT INTO town VALUES (1552,9,'Zazuar');
INSERT INTO town VALUES (1553,9,'Zuñeda');
INSERT INTO town VALUES (1554,10,'Abadía');
INSERT INTO town VALUES (1555,10,'Abertura');
INSERT INTO town VALUES (1556,10,'Acebo');
INSERT INTO town VALUES (1557,10,'Acehúche');
INSERT INTO town VALUES (1558,10,'Aceituna');
INSERT INTO town VALUES (1559,10,'Ahigal');
INSERT INTO town VALUES (1560,10,'Albalá');
INSERT INTO town VALUES (1561,10,'Alcántara');
INSERT INTO town VALUES (1562,10,'Alcollarín');
INSERT INTO town VALUES (1563,10,'Alcuéscar');
INSERT INTO town VALUES (1564,10,'Aldea del Cano');
INSERT INTO town VALUES (1565,10,'Aldea del Obispo (La)');
INSERT INTO town VALUES (1566,10,'Aldeacentenera');
INSERT INTO town VALUES (1567,10,'Aldeanueva de la Vera');
INSERT INTO town VALUES (1568,10,'Aldeanueva del Camino');
INSERT INTO town VALUES (1569,10,'Aldehuela de Jerte');
INSERT INTO town VALUES (1570,10,'Alía');
INSERT INTO town VALUES (1571,10,'Aliseda');
INSERT INTO town VALUES (1572,10,'Almaraz');
INSERT INTO town VALUES (1573,10,'Almoharín');
INSERT INTO town VALUES (1574,10,'Arroyo de la Luz');
INSERT INTO town VALUES (1575,10,'Arroyomolinos');
INSERT INTO town VALUES (1576,10,'Arroyomolinos de la Vera');
INSERT INTO town VALUES (1577,10,'Baños de Montemayor');
INSERT INTO town VALUES (1578,10,'Barrado');
INSERT INTO town VALUES (1579,10,'Belvís de Monroy');
INSERT INTO town VALUES (1580,10,'Benquerencia');
INSERT INTO town VALUES (1581,10,'Berrocalejo');
INSERT INTO town VALUES (1582,10,'Berzocana');
INSERT INTO town VALUES (1583,10,'Bohonal de Ibor');
INSERT INTO town VALUES (1584,10,'Botija');
INSERT INTO town VALUES (1585,10,'Brozas');
INSERT INTO town VALUES (1586,10,'Cabañas del Castillo');
INSERT INTO town VALUES (1587,10,'Cabezabellosa');
INSERT INTO town VALUES (1588,10,'Cabezuela del Valle');
INSERT INTO town VALUES (1589,10,'Cabrero');
INSERT INTO town VALUES (1590,10,'Cáceres');
INSERT INTO town VALUES (1591,10,'Cachorrilla');
INSERT INTO town VALUES (1592,10,'Cadalso');
INSERT INTO town VALUES (1593,10,'Calzadilla');
INSERT INTO town VALUES (1594,10,'Caminomorisco');
INSERT INTO town VALUES (1595,10,'Campillo de Deleitosa');
INSERT INTO town VALUES (1596,10,'Campo Lugar');
INSERT INTO town VALUES (1597,10,'Cañamero');
INSERT INTO town VALUES (1598,10,'Cañaveral');
INSERT INTO town VALUES (1599,10,'Carbajo');
INSERT INTO town VALUES (1600,10,'Carcaboso');
INSERT INTO town VALUES (1601,10,'Carrascalejo');
INSERT INTO town VALUES (1602,10,'Casar de Cáceres');
INSERT INTO town VALUES (1603,10,'Casar de Palomero');
INSERT INTO town VALUES (1604,10,'Casares de las Hurdes');
INSERT INTO town VALUES (1605,10,'Casas de Don Antonio');
INSERT INTO town VALUES (1606,10,'Casas de Don Gómez');
INSERT INTO town VALUES (1607,10,'Casas de Millán');
INSERT INTO town VALUES (1608,10,'Casas de Miravete');
INSERT INTO town VALUES (1609,10,'Casas del Castañar');
INSERT INTO town VALUES (1610,10,'Casas del Monte');
INSERT INTO town VALUES (1611,10,'Casatejada');
INSERT INTO town VALUES (1612,10,'Casillas de Coria');
INSERT INTO town VALUES (1613,10,'Castañar de Ibor');
INSERT INTO town VALUES (1614,10,'Ceclavín');
INSERT INTO town VALUES (1615,10,'Cedillo');
INSERT INTO town VALUES (1616,10,'Cerezo');
INSERT INTO town VALUES (1617,10,'Cilleros');
INSERT INTO town VALUES (1618,10,'Collado');
INSERT INTO town VALUES (1619,10,'Conquista de la Sierra');
INSERT INTO town VALUES (1620,10,'Coria');
INSERT INTO town VALUES (1621,10,'Cuacos de Yuste');
INSERT INTO town VALUES (1622,10,'Cumbre (La)');
INSERT INTO town VALUES (1623,10,'Deleitosa');
INSERT INTO town VALUES (1624,10,'Descargamaría');
INSERT INTO town VALUES (1625,10,'Eljas');
INSERT INTO town VALUES (1626,10,'Escurial');
INSERT INTO town VALUES (1627,10,'Fresnedoso de Ibor');
INSERT INTO town VALUES (1628,10,'Galisteo');
INSERT INTO town VALUES (1629,10,'Garciaz');
INSERT INTO town VALUES (1630,10,'Garganta (La)');
INSERT INTO town VALUES (1631,10,'Garganta la Olla');
INSERT INTO town VALUES (1632,10,'Gargantilla');
INSERT INTO town VALUES (1633,10,'Gargüera');
INSERT INTO town VALUES (1634,10,'Garrovillas de Alconétar');
INSERT INTO town VALUES (1635,10,'Garvín');
INSERT INTO town VALUES (1636,10,'Gata');
INSERT INTO town VALUES (1637,10,'Gordo (El)');
INSERT INTO town VALUES (1638,10,'Granja (La)');
INSERT INTO town VALUES (1639,10,'Guadalupe');
INSERT INTO town VALUES (1640,10,'Guijo de Coria');
INSERT INTO town VALUES (1641,10,'Guijo de Galisteo');
INSERT INTO town VALUES (1642,10,'Guijo de Granadilla');
INSERT INTO town VALUES (1643,10,'Guijo de Santa Bárbara');
INSERT INTO town VALUES (1644,10,'Herguijuela');
INSERT INTO town VALUES (1645,10,'Hernán-Pérez');
INSERT INTO town VALUES (1646,10,'Herrera de Alcántara');
INSERT INTO town VALUES (1647,10,'Herreruela');
INSERT INTO town VALUES (1648,10,'Hervás');
INSERT INTO town VALUES (1649,10,'Higuera');
INSERT INTO town VALUES (1650,10,'Hinojal');
INSERT INTO town VALUES (1651,10,'Holguera');
INSERT INTO town VALUES (1652,10,'Hoyos');
INSERT INTO town VALUES (1653,10,'Huélaga');
INSERT INTO town VALUES (1654,10,'Ibahernando');
INSERT INTO town VALUES (1655,10,'Jaraicejo');
INSERT INTO town VALUES (1656,10,'Jaraíz de la Vera');
INSERT INTO town VALUES (1657,10,'Jarandilla de la Vera');
INSERT INTO town VALUES (1658,10,'Jarilla');
INSERT INTO town VALUES (1659,10,'Jerte');
INSERT INTO town VALUES (1660,10,'Ladrillar');
INSERT INTO town VALUES (1661,10,'Logrosán');
INSERT INTO town VALUES (1662,10,'Losar de la Vera');
INSERT INTO town VALUES (1663,10,'Madrigal de la Vera');
INSERT INTO town VALUES (1664,10,'Madrigalejo');
INSERT INTO town VALUES (1665,10,'Madroñera');
INSERT INTO town VALUES (1666,10,'Majadas');
INSERT INTO town VALUES (1667,10,'Malpartida de Cáceres');
INSERT INTO town VALUES (1668,10,'Malpartida de Plasencia');
INSERT INTO town VALUES (1669,10,'Marchagaz');
INSERT INTO town VALUES (1670,10,'Mata de Alcántara');
INSERT INTO town VALUES (1671,10,'Membrío');
INSERT INTO town VALUES (1672,10,'Mesas de Ibor');
INSERT INTO town VALUES (1673,10,'Miajadas');
INSERT INTO town VALUES (1674,10,'Millanes');
INSERT INTO town VALUES (1675,10,'Mirabel');
INSERT INTO town VALUES (1676,10,'Mohedas de Granadilla');
INSERT INTO town VALUES (1677,10,'Monroy');
INSERT INTO town VALUES (1678,10,'Montánchez');
INSERT INTO town VALUES (1679,10,'Montehermoso');
INSERT INTO town VALUES (1680,10,'Moraleja');
INSERT INTO town VALUES (1681,10,'Morcillo');
INSERT INTO town VALUES (1682,10,'Navaconcejo');
INSERT INTO town VALUES (1683,10,'Navalmoral de la Mata');
INSERT INTO town VALUES (1684,10,'Navalvillar de Ibor');
INSERT INTO town VALUES (1685,10,'Navas del Madroño');
INSERT INTO town VALUES (1686,10,'Navezuelas');
INSERT INTO town VALUES (1687,10,'Nuñomoral');
INSERT INTO town VALUES (1688,10,'Oliva de Plasencia');
INSERT INTO town VALUES (1689,10,'Palomero');
INSERT INTO town VALUES (1690,10,'Pasarón de la Vera');
INSERT INTO town VALUES (1691,10,'Pedroso de Acim');
INSERT INTO town VALUES (1692,10,'Peraleda de la Mata');
INSERT INTO town VALUES (1693,10,'Peraleda de San Román');
INSERT INTO town VALUES (1694,10,'Perales del Puerto');
INSERT INTO town VALUES (1695,10,'Pescueza');
INSERT INTO town VALUES (1696,10,'Pesga (La)');
INSERT INTO town VALUES (1697,10,'Piedras Albas');
INSERT INTO town VALUES (1698,10,'Pinofranqueado');
INSERT INTO town VALUES (1699,10,'Piornal');
INSERT INTO town VALUES (1700,10,'Plasencia');
INSERT INTO town VALUES (1701,10,'Plasenzuela');
INSERT INTO town VALUES (1702,10,'Portaje');
INSERT INTO town VALUES (1703,10,'Portezuelo');
INSERT INTO town VALUES (1704,10,'Pozuelo de Zarzón');
INSERT INTO town VALUES (1705,10,'Puerto de Santa Cruz');
INSERT INTO town VALUES (1706,10,'Rebollar');
INSERT INTO town VALUES (1707,10,'Riolobos');
INSERT INTO town VALUES (1708,10,'Robledillo de Gata');
INSERT INTO town VALUES (1709,10,'Robledillo de la Vera');
INSERT INTO town VALUES (1710,10,'Robledillo de Trujillo');
INSERT INTO town VALUES (1711,10,'Robledollano');
INSERT INTO town VALUES (1712,10,'Romangordo');
INSERT INTO town VALUES (1713,10,'Rosalejo');
INSERT INTO town VALUES (1714,10,'Ruanes');
INSERT INTO town VALUES (1715,10,'Salorino');
INSERT INTO town VALUES (1716,10,'Salvatierra de Santiago');
INSERT INTO town VALUES (1717,10,'San Martín de Trevejo');
INSERT INTO town VALUES (1718,10,'Santa Ana');
INSERT INTO town VALUES (1719,10,'Santa Cruz de la Sierra');
INSERT INTO town VALUES (1720,10,'Santa Cruz de Paniagua');
INSERT INTO town VALUES (1721,10,'Santa Marta de Magasca');
INSERT INTO town VALUES (1722,10,'Santiago de Alcántara');
INSERT INTO town VALUES (1723,10,'Santiago del Campo');
INSERT INTO town VALUES (1724,10,'Santibáñez el Alto');
INSERT INTO town VALUES (1725,10,'Santibáñez el Bajo');
INSERT INTO town VALUES (1726,10,'Saucedilla');
INSERT INTO town VALUES (1727,10,'Segura de Toro');
INSERT INTO town VALUES (1728,10,'Serradilla');
INSERT INTO town VALUES (1729,10,'Serrejón');
INSERT INTO town VALUES (1730,10,'Sierra de Fuentes');
INSERT INTO town VALUES (1731,10,'Talaván');
INSERT INTO town VALUES (1732,10,'Talaveruela de la Vera');
INSERT INTO town VALUES (1733,10,'Talayuela');
INSERT INTO town VALUES (1734,10,'Tejeda de Tiétar');
INSERT INTO town VALUES (1735,10,'Toril');
INSERT INTO town VALUES (1736,10,'Tornavacas');
INSERT INTO town VALUES (1737,10,'Torno (El)');
INSERT INTO town VALUES (1738,10,'Torre de Don Miguel');
INSERT INTO town VALUES (1739,10,'Torre de Santa María');
INSERT INTO town VALUES (1740,10,'Torrecilla de los Ángeles');
INSERT INTO town VALUES (1741,10,'Torrecillas de la Tiesa');
INSERT INTO town VALUES (1742,10,'Torrejón el Rubio');
INSERT INTO town VALUES (1743,10,'Torrejoncillo');
INSERT INTO town VALUES (1744,10,'Torremenga');
INSERT INTO town VALUES (1745,10,'Torremocha');
INSERT INTO town VALUES (1746,10,'Torreorgaz');
INSERT INTO town VALUES (1747,10,'Torrequemada');
INSERT INTO town VALUES (1748,10,'Trujillo');
INSERT INTO town VALUES (1749,10,'Valdastillas');
INSERT INTO town VALUES (1750,10,'Valdecañas de Tajo');
INSERT INTO town VALUES (1751,10,'Valdefuentes');
INSERT INTO town VALUES (1752,10,'Valdehúncar');
INSERT INTO town VALUES (1753,10,'Valdelacasa de Tajo');
INSERT INTO town VALUES (1754,10,'Valdemorales');
INSERT INTO town VALUES (1755,10,'Valdeobispo');
INSERT INTO town VALUES (1756,10,'Valencia de Alcántara');
INSERT INTO town VALUES (1757,10,'Valverde de la Vera');
INSERT INTO town VALUES (1758,10,'Valverde del Fresno');
INSERT INTO town VALUES (1759,10,'Viandar de la Vera');
INSERT INTO town VALUES (1760,10,'Villa del Campo');
INSERT INTO town VALUES (1761,10,'Villa del Rey');
INSERT INTO town VALUES (1762,10,'Villamesías');
INSERT INTO town VALUES (1763,10,'Villamiel');
INSERT INTO town VALUES (1764,10,'Villanueva de la Sierra');
INSERT INTO town VALUES (1765,10,'Villanueva de la Vera');
INSERT INTO town VALUES (1766,10,'Villar de Plasencia');
INSERT INTO town VALUES (1767,10,'Villar del Pedroso');
INSERT INTO town VALUES (1768,10,'Villasbuenas de Gata');
INSERT INTO town VALUES (1769,10,'Zarza de Granadilla');
INSERT INTO town VALUES (1770,10,'Zarza de Montánchez');
INSERT INTO town VALUES (1771,10,'Zarza la Mayor');
INSERT INTO town VALUES (1772,10,'Zorita');
INSERT INTO town VALUES (1773,11,'Alcalá de los Gazules');
INSERT INTO town VALUES (1774,11,'Alcalá del Valle');
INSERT INTO town VALUES (1775,11,'Algar');
INSERT INTO town VALUES (1776,11,'Algeciras');
INSERT INTO town VALUES (1777,11,'Algodonales');
INSERT INTO town VALUES (1778,11,'Arcos de la Frontera');
INSERT INTO town VALUES (1779,11,'Barbate');
INSERT INTO town VALUES (1780,11,'Barrios (Los)');
INSERT INTO town VALUES (1781,11,'Benalup-Casas Viejas');
INSERT INTO town VALUES (1782,11,'Benaocaz');
INSERT INTO town VALUES (1783,11,'Bornos');
INSERT INTO town VALUES (1784,11,'Bosque (El)');
INSERT INTO town VALUES (1785,11,'Cádiz');
INSERT INTO town VALUES (1786,11,'Castellar de la Frontera');
INSERT INTO town VALUES (1787,11,'Chiclana de la Frontera');
INSERT INTO town VALUES (1788,11,'Chipiona');
INSERT INTO town VALUES (1789,11,'Conil de la Frontera');
INSERT INTO town VALUES (1790,11,'Espera');
INSERT INTO town VALUES (1791,11,'Gastor (El)');
INSERT INTO town VALUES (1792,11,'Grazalema');
INSERT INTO town VALUES (1793,11,'Jerez de la Frontera');
INSERT INTO town VALUES (1794,11,'Jimena de la Frontera');
INSERT INTO town VALUES (1795,11,'Línea de la Concepción (La)');
INSERT INTO town VALUES (1796,11,'Medina-Sidonia');
INSERT INTO town VALUES (1797,11,'Olvera');
INSERT INTO town VALUES (1798,11,'Paterna de Rivera');
INSERT INTO town VALUES (1799,11,'Prado del Rey');
INSERT INTO town VALUES (1800,11,'Puerto de Santa María (El)');
INSERT INTO town VALUES (1801,11,'Puerto Real');
INSERT INTO town VALUES (1802,11,'Puerto Serrano');
INSERT INTO town VALUES (1803,11,'Rota');
INSERT INTO town VALUES (1804,11,'San Fernando');
INSERT INTO town VALUES (1805,11,'San José del Valle');
INSERT INTO town VALUES (1806,11,'San Roque');
INSERT INTO town VALUES (1807,11,'Sanlúcar de Barrameda');
INSERT INTO town VALUES (1808,11,'Setenil de las Bodegas');
INSERT INTO town VALUES (1809,11,'Tarifa');
INSERT INTO town VALUES (1810,11,'Torre Alháquime');
INSERT INTO town VALUES (1811,11,'Trebujena');
INSERT INTO town VALUES (1812,11,'Ubrique');
