INSERT INTO town VALUES (1,1,'Alegría-Dulantzi');
INSERT INTO town VALUES (2,1,'Amurrio');
INSERT INTO town VALUES (3,1,'Añana');
INSERT INTO town VALUES (4,1,'Aramaio');
INSERT INTO town VALUES (5,1,'Armiñón');
INSERT INTO town VALUES (6,1,'Arraia-Maeztu');
INSERT INTO town VALUES (7,1,'Arrazua-Ubarrundia');
INSERT INTO town VALUES (8,1,'Artziniega');
INSERT INTO town VALUES (9,1,'Asparrena');
INSERT INTO town VALUES (10,1,'Ayala/Aiara');
INSERT INTO town VALUES (11,1,'Baños de Ebro/Mañueta');
INSERT INTO town VALUES (12,1,'Alegría-Dulantzi');
INSERT INTO town VALUES (13,1,'Amurrio');
INSERT INTO town VALUES (14,1,'Añana');
INSERT INTO town VALUES (15,1,'Aramaio');
INSERT INTO town VALUES (16,1,'Armiñón');
INSERT INTO town VALUES (17,1,'Arraia-Maeztu');
INSERT INTO town VALUES (18,1,'Arrazua-Ubarrundia');
INSERT INTO town VALUES (19,1,'Artziniega');
INSERT INTO town VALUES (20,1,'Asparrena');
INSERT INTO town VALUES (21,1,'Ayala/Aiara');
INSERT INTO town VALUES (22,1,'Baños de Ebro/Mañueta');
INSERT INTO town VALUES (23,1,'Barrundia');
INSERT INTO town VALUES (24,1,'Berantevilla');
INSERT INTO town VALUES (25,1,'Bernedo');
INSERT INTO town VALUES (26,1,'Campezo/Kanpezu');
INSERT INTO town VALUES (27,1,'Elburgo/Burgelu');
INSERT INTO town VALUES (28,1,'Elciego');
INSERT INTO town VALUES (29,1,'Elvillar/Bilar');
INSERT INTO town VALUES (30,1,'Harana/Valle de Arana');
INSERT INTO town VALUES (31,1,'Iruña Oka/Iruña de Oca');
INSERT INTO town VALUES (32,1,'Iruraiz-Gauna');
INSERT INTO town VALUES (33,1,'Kripan');
INSERT INTO town VALUES (34,1,'Kuartango');
INSERT INTO town VALUES (35,1,'Labastida/Bastida');
INSERT INTO town VALUES (36,1,'Lagrán');
INSERT INTO town VALUES (37,1,'Laguardia');
INSERT INTO town VALUES (38,1,'Lanciego/Lantziego');
INSERT INTO town VALUES (39,1,'Lantarón');
INSERT INTO town VALUES (40,1,'Lapuebla de Labarca');
INSERT INTO town VALUES (41,1,'Laudio/Llodio');
INSERT INTO town VALUES (42,1,'Legutiano');
INSERT INTO town VALUES (43,1,'Leza');
INSERT INTO town VALUES (44,1,'Moreda de Álava');
INSERT INTO town VALUES (45,1,'Navaridas');
INSERT INTO town VALUES (46,1,'Okondo');
INSERT INTO town VALUES (47,1,'Oyón-Oion');
INSERT INTO town VALUES (48,1,'Peñacerrada-Urizaharra');
INSERT INTO town VALUES (49,1,'Ribera Alta');
INSERT INTO town VALUES (50,1,'Ribera Baja/Erribera Beitia');
INSERT INTO town VALUES (51,1,'Salvatierra/Agurain');
INSERT INTO town VALUES (52,1,'Samaniego');
INSERT INTO town VALUES (53,1,'San Millán/Donemiliaga');
INSERT INTO town VALUES (54,1,'Urkabustaiz');
INSERT INTO town VALUES (55,1,'Valdegovía/Gaubea');
INSERT INTO town VALUES (56,1,'Villabuena de Álava/Eskuernaga');
INSERT INTO town VALUES (57,1,'Vitoria-Gasteiz');
INSERT INTO town VALUES (58,1,'Yécora/Iekora');
INSERT INTO town VALUES (59,1,'Zalduondo');
INSERT INTO town VALUES (60,1,'Zambrana');
INSERT INTO town VALUES (61,1,'Zigoitia');
INSERT INTO town VALUES (62,1,'Zuia');
INSERT INTO town VALUES (63,2,'Abengibre');
INSERT INTO town VALUES (64,2,'Alatoz');
INSERT INTO town VALUES (65,2,'Albacete');
INSERT INTO town VALUES (66,2,'Albatana');
INSERT INTO town VALUES (67,2,'Alborea');
INSERT INTO town VALUES (68,2,'Alcadozo');
INSERT INTO town VALUES (69,2,'Alcalá del Júcar');
INSERT INTO town VALUES (70,2,'Alcaraz');
INSERT INTO town VALUES (71,2,'Almansa');
INSERT INTO town VALUES (72,2,'Alpera');
INSERT INTO town VALUES (73,2,'Ayna');
INSERT INTO town VALUES (74,2,'Balazote');
INSERT INTO town VALUES (75,2,'Ballestero (El)');
INSERT INTO town VALUES (76,2,'Balsa de Ves');
INSERT INTO town VALUES (77,2,'Barrax');
INSERT INTO town VALUES (78,2,'Bienservida');
INSERT INTO town VALUES (79,2,'Bogarra');
INSERT INTO town VALUES (80,2,'Bonete');
INSERT INTO town VALUES (81,2,'Bonillo (El)');
INSERT INTO town VALUES (82,2,'Carcelén');
INSERT INTO town VALUES (83,2,'Casas de Juan Núñez');
INSERT INTO town VALUES (84,2,'Casas de Lázaro');
INSERT INTO town VALUES (85,2,'Casas de Ves');
INSERT INTO town VALUES (86,2,'Casas-Ibáñez');
INSERT INTO town VALUES (87,2,'Caudete');
INSERT INTO town VALUES (88,2,'Cenizate');
INSERT INTO town VALUES (89,2,'Chinchilla de Monte-Aragón');
INSERT INTO town VALUES (90,2,'Corral-Rubio');
INSERT INTO town VALUES (91,2,'Cotillas');
INSERT INTO town VALUES (92,2,'Elche de la Sierra');
INSERT INTO town VALUES (93,2,'Férez');
INSERT INTO town VALUES (94,2,'Fuensanta');
INSERT INTO town VALUES (95,2,'Fuente-Álamo');
INSERT INTO town VALUES (96,2,'Fuentealbilla');
INSERT INTO town VALUES (97,2,'Gineta (La)');
INSERT INTO town VALUES (98,2,'Golosalvo');
INSERT INTO town VALUES (99,2,'Hellín');
INSERT INTO town VALUES (100,2,'Herrera (La)');
INSERT INTO town VALUES (101,2,'Higueruela');
INSERT INTO town VALUES (102,2,'Hoya-Gonzalo');
INSERT INTO town VALUES (103,2,'Jorquera');
INSERT INTO town VALUES (104,2,'Letur');
INSERT INTO town VALUES (105,2,'Lezuza');
INSERT INTO town VALUES (106,2,'Liétor');
INSERT INTO town VALUES (107,2,'Madrigueras');
INSERT INTO town VALUES (108,2,'Mahora');
INSERT INTO town VALUES (109,2,'Masegoso');
INSERT INTO town VALUES (110,2,'Minaya');
INSERT INTO town VALUES (111,2,'Molinicos');
INSERT INTO town VALUES (112,2,'Montalvos');
INSERT INTO town VALUES (113,2,'Montealegre del Castillo');
INSERT INTO town VALUES (114,2,'Motilleja');
INSERT INTO town VALUES (115,2,'Munera');
INSERT INTO town VALUES (116,2,'Navas de Jorquera');
INSERT INTO town VALUES (117,2,'Nerpio');
INSERT INTO town VALUES (118,2,'Ontur');
INSERT INTO town VALUES (119,2,'Ossa de Montiel');
INSERT INTO town VALUES (120,2,'Paterna del Madera');
INSERT INTO town VALUES (121,2,'Peñas de San Pedro');
INSERT INTO town VALUES (122,2,'Peñascosa');
INSERT INTO town VALUES (123,2,'Pétrola');
INSERT INTO town VALUES (124,2,'Povedilla');
INSERT INTO town VALUES (125,2,'Pozo Cañada');
INSERT INTO town VALUES (126,2,'Pozohondo');
INSERT INTO town VALUES (127,2,'Pozo-Lorente');
INSERT INTO town VALUES (128,2,'Pozuelo');
INSERT INTO town VALUES (129,2,'Recueja (La)');
INSERT INTO town VALUES (130,2,'Riópar');
INSERT INTO town VALUES (131,2,'Robledo');
INSERT INTO town VALUES (132,2,'Roda (La)');
INSERT INTO town VALUES (133,2,'Salobre');
INSERT INTO town VALUES (134,2,'San Pedro');
INSERT INTO town VALUES (135,2,'Socovos');
INSERT INTO town VALUES (136,2,'Tarazona de la Mancha');
INSERT INTO town VALUES (137,2,'Tobarra');
INSERT INTO town VALUES (138,2,'Valdeganga');
INSERT INTO town VALUES (139,2,'Vianos');
INSERT INTO town VALUES (140,2,'Villa de Ves');
INSERT INTO town VALUES (141,2,'Villalgordo del Júcar');
INSERT INTO town VALUES (142,2,'Villamalea');
INSERT INTO town VALUES (143,2,'Villapalacios');
INSERT INTO town VALUES (144,2,'Villarrobledo');
INSERT INTO town VALUES (145,2,'Villatoya');
INSERT INTO town VALUES (146,2,'Villavaliente');
INSERT INTO town VALUES (147,2,'Villaverde de Guadalimar');
INSERT INTO town VALUES (148,2,'Viveros');
INSERT INTO town VALUES (149,2,'Yeste');
INSERT INTO town VALUES (150,3,'Adsubia');
INSERT INTO town VALUES (151,3,'Agost');
INSERT INTO town VALUES (152,3,'Agres');
INSERT INTO town VALUES (153,3,'Aigües');
INSERT INTO town VALUES (154,3,'Albatera');
INSERT INTO town VALUES (155,3,'Alcalalí');
INSERT INTO town VALUES (156,3,'Alcocer de Planes');
INSERT INTO town VALUES (157,3,'Alcoleja');
INSERT INTO town VALUES (158,3,'Alcoy/Alcoi');
INSERT INTO town VALUES (159,3,'Alfafara');
INSERT INTO town VALUES (160,3,'Alfàs del Pi ');
INSERT INTO town VALUES (161,3,'Algorfa');
INSERT INTO town VALUES (162,3,'Algueña');
INSERT INTO town VALUES (163,3,'Alicante/Alacant');
INSERT INTO town VALUES (164,3,'Almoradí');
INSERT INTO town VALUES (165,3,'Almudaina');
INSERT INTO town VALUES (166,3,'Alqueria deAsnar ');
INSERT INTO town VALUES (167,3,'Altea');
INSERT INTO town VALUES (168,3,'Aspe');
INSERT INTO town VALUES (169,3,'Balones');
INSERT INTO town VALUES (170,3,'Banyeres de Mariola');
INSERT INTO town VALUES (171,3,'Benasau');
INSERT INTO town VALUES (172,3,'Beneixama');
INSERT INTO town VALUES (173,3,'Benejúzar');
INSERT INTO town VALUES (174,3,'Benferri');
INSERT INTO town VALUES (175,3,'Beniarbeig');
INSERT INTO town VALUES (176,3,'Beniardá');
INSERT INTO town VALUES (177,3,'Beniarrés');
INSERT INTO town VALUES (178,3,'Benidoleig');
INSERT INTO town VALUES (179,3,'Benidorm');
INSERT INTO town VALUES (180,3,'Benifallim');
INSERT INTO town VALUES (181,3,'Benifato');
INSERT INTO town VALUES (182,3,'Benigembla');
INSERT INTO town VALUES (183,3,'Benijófar');
INSERT INTO town VALUES (184,3,'Benilloba');
INSERT INTO town VALUES (185,3,'Benillup');
INSERT INTO town VALUES (186,3,'Benimantell');
INSERT INTO town VALUES (187,3,'Benimarfull');
INSERT INTO town VALUES (188,3,'Benimassot');
INSERT INTO town VALUES (189,3,'Benimeli');
INSERT INTO town VALUES (190,3,'Benissa');
INSERT INTO town VALUES (191,3,'Benitachell/Poble Nou de Benitatxell (el)');
INSERT INTO town VALUES (192,3,'Biar');
INSERT INTO town VALUES (193,3,'Bigastro');
INSERT INTO town VALUES (194,3,'Bolulla');
INSERT INTO town VALUES (195,3,'Busot');
INSERT INTO town VALUES (196,3,'Callosa de Segura');
INSERT INTO town VALUES (197,3,'Callosa deEn Sarrià');
INSERT INTO town VALUES (198,3,'Calpe/Calp');
INSERT INTO town VALUES (199,3,'Campello (el)');
INSERT INTO town VALUES (200,3,'Campo de Mirra/Camp de Mirra (el)');
INSERT INTO town VALUES (201,3,'Cañada');
INSERT INTO town VALUES (202,3,'Castalla');
INSERT INTO town VALUES (203,3,'Castell de Castells');
INSERT INTO town VALUES (204,3,'Castell de Guadalest (el)');
INSERT INTO town VALUES (205,3,'Catral');
INSERT INTO town VALUES (206,3,'Cocentaina');
INSERT INTO town VALUES (207,3,'Confrides');
INSERT INTO town VALUES (208,3,'Cox');
INSERT INTO town VALUES (209,3,'Crevillent');
INSERT INTO town VALUES (210,3,'Daya Nueva');
INSERT INTO town VALUES (211,3,'Daya Vieja');
INSERT INTO town VALUES (212,3,'Dénia');
INSERT INTO town VALUES (213,3,'Dolores');
INSERT INTO town VALUES (214,3,'Elche/Elx');
INSERT INTO town VALUES (215,3,'Elda');
INSERT INTO town VALUES (216,3,'Facheca');
INSERT INTO town VALUES (217,3,'Famorca');
INSERT INTO town VALUES (218,3,'Finestrat');
INSERT INTO town VALUES (219,3,'Fondó de les Neus (el)');
INSERT INTO town VALUES (220,3,'Formentera del Segura');
INSERT INTO town VALUES (221,3,'Gaianes');
INSERT INTO town VALUES (222,3,'Gata de Gorgos');
INSERT INTO town VALUES (223,3,'Gorga');
INSERT INTO town VALUES (224,3,'Granja de Rocamora');
INSERT INTO town VALUES (225,3,'Guardamar del Segura');
INSERT INTO town VALUES (226,3,'Hondón de los Frailes');
INSERT INTO town VALUES (227,3,'Ibi');
INSERT INTO town VALUES (228,3,'Jacarilla');
INSERT INTO town VALUES (229,3,'Jalón/Xaló');
INSERT INTO town VALUES (230,3,'Jávea/Xàbia');
INSERT INTO town VALUES (231,3,'Jijona/Xixona');
INSERT INTO town VALUES (232,3,'Llíber');
INSERT INTO town VALUES (233,3,'Lorcha/Orxa ');
INSERT INTO town VALUES (234,3,'Millena');
INSERT INTO town VALUES (235,3,'Monforte del Cid');
INSERT INTO town VALUES (236,3,'Monóvar/Monòver');
INSERT INTO town VALUES (237,3,'Montesinos (Los)');
INSERT INTO town VALUES (238,3,'Murla');
INSERT INTO town VALUES (239,3,'Muro de Alcoy');
INSERT INTO town VALUES (240,3,'Mutxamel');
INSERT INTO town VALUES (241,3,'Novelda');
INSERT INTO town VALUES (242,3,'Nucia (la)');
INSERT INTO town VALUES (243,3,'Ondara');
INSERT INTO town VALUES (244,3,'Onil');
INSERT INTO town VALUES (245,3,'Orba');
INSERT INTO town VALUES (246,3,'Orihuela');
INSERT INTO town VALUES (247,3,'Orxeta');
INSERT INTO town VALUES (248,3,'Parcent');
INSERT INTO town VALUES (249,3,'Pedreguer');
INSERT INTO town VALUES (250,3,'Pego');
INSERT INTO town VALUES (251,3,'Penàguila');
INSERT INTO town VALUES (252,3,'Petrer');
INSERT INTO town VALUES (253,3,'Pilar de la Horadada');
INSERT INTO town VALUES (254,3,'Pinós (el)/Pinoso');
INSERT INTO town VALUES (255,3,'Planes');
INSERT INTO town VALUES (256,3,'Poblets (els)');
INSERT INTO town VALUES (257,3,'Polop');
INSERT INTO town VALUES (258,3,'Quatretondeta');
INSERT INTO town VALUES (259,3,'Rafal');
INSERT INTO town VALUES (260,3,'Ràfol deAlmúnia (El)');
INSERT INTO town VALUES (261,3,'Redován');
INSERT INTO town VALUES (262,3,'Relleu');
INSERT INTO town VALUES (263,3,'Rojales');
INSERT INTO town VALUES (264,3,'Romana (la)');
INSERT INTO town VALUES (265,3,'Sagra');
INSERT INTO town VALUES (266,3,'Salinas');
INSERT INTO town VALUES (267,3,'San Fulgencio');
INSERT INTO town VALUES (268,3,'San Isidro');
INSERT INTO town VALUES (269,3,'San Miguel de Salinas');
INSERT INTO town VALUES (270,3,'San Vicente del Raspeig/Sant Vicent del Raspeig');
INSERT INTO town VALUES (271,3,'Sanet y Negrals');
INSERT INTO town VALUES (272,3,'Sant Joan deAlacant');
INSERT INTO town VALUES (273,3,'Santa Pola');
INSERT INTO town VALUES (274,3,'Sax');
INSERT INTO town VALUES (275,3,'Sella');
INSERT INTO town VALUES (276,3,'Senija');
INSERT INTO town VALUES (277,3,'Tàrbena');
INSERT INTO town VALUES (278,3,'Teulada');
INSERT INTO town VALUES (279,3,'Tibi');
INSERT INTO town VALUES (280,3,'Tollos');
INSERT INTO town VALUES (281,3,'Tormos');
INSERT INTO town VALUES (282,3,'Torremanzanas/Torre de les Maçanes (la)');
INSERT INTO town VALUES (283,3,'Torrevieja');
INSERT INTO town VALUES (284,3,'Vall deAlcalà (la)');
INSERT INTO town VALUES (285,3,'Vall de Ebo');
INSERT INTO town VALUES (286,3,'Vall de Gallinera');
INSERT INTO town VALUES (287,3,'Vall de Laguar (la)');
INSERT INTO town VALUES (288,3,'Verger (el)');
INSERT INTO town VALUES (289,3,'Villajoyosa/Vila Joiosa (la)');
INSERT INTO town VALUES (290,3,'Villena');
INSERT INTO town VALUES (291,4,'Abla');
INSERT INTO town VALUES (292,4,'Abrucena');
INSERT INTO town VALUES (293,4,'Adra');
INSERT INTO town VALUES (294,4,'Albánchez');
INSERT INTO town VALUES (295,4,'Alboloduy');
INSERT INTO town VALUES (296,4,'Albox');
INSERT INTO town VALUES (297,4,'Alcolea');
INSERT INTO town VALUES (298,4,'Alcóntar');
INSERT INTO town VALUES (299,4,'Alcudia de Monteagud');
INSERT INTO town VALUES (300,4,'Alhabia');
INSERT INTO town VALUES (301,4,'Alhama de Almería');
INSERT INTO town VALUES (302,4,'Alicún');
INSERT INTO town VALUES (303,4,'Almería');
INSERT INTO town VALUES (304,4,'Almócita');
INSERT INTO town VALUES (305,4,'Alsodux');
INSERT INTO town VALUES (306,4,'Antas');
INSERT INTO town VALUES (307,4,'Arboleas');
INSERT INTO town VALUES (308,4,'Armuña de Almanzora');
INSERT INTO town VALUES (309,4,'Bacares');
INSERT INTO town VALUES (310,4,'Bayárcal');
INSERT INTO town VALUES (311,4,'Bayarque');
INSERT INTO town VALUES (312,4,'Bédar');
INSERT INTO town VALUES (313,4,'Beires');
INSERT INTO town VALUES (314,4,'Benahadux');
INSERT INTO town VALUES (315,4,'Benitagla');
INSERT INTO town VALUES (316,4,'Benizalón');
INSERT INTO town VALUES (317,4,'Bentarique');
INSERT INTO town VALUES (318,4,'Berja');
INSERT INTO town VALUES (319,4,'Canjáyar');
INSERT INTO town VALUES (320,4,'Cantoria');
INSERT INTO town VALUES (321,4,'Carboneras');
INSERT INTO town VALUES (322,4,'Castro de Filabres');
INSERT INTO town VALUES (323,4,'Chercos');
INSERT INTO town VALUES (324,4,'Chirivel');
INSERT INTO town VALUES (325,4,'Cóbdar');
INSERT INTO town VALUES (326,4,'Cuevas del Almanzora');
INSERT INTO town VALUES (327,4,'Dalías');
INSERT INTO town VALUES (328,4,'Ejido (El)');
INSERT INTO town VALUES (329,4,'Enix');
INSERT INTO town VALUES (330,4,'Felix');
INSERT INTO town VALUES (331,4,'Fines');
INSERT INTO town VALUES (332,4,'Fiñana');
INSERT INTO town VALUES (333,4,'Fondón');
INSERT INTO town VALUES (334,4,'Gádor');
INSERT INTO town VALUES (335,4,'Gallardos (Los)');
INSERT INTO town VALUES (336,4,'Garrucha');
INSERT INTO town VALUES (337,4,'Gérgal');
INSERT INTO town VALUES (338,4,'Huécija');
INSERT INTO town VALUES (339,4,'Huércal de Almería');
INSERT INTO town VALUES (340,4,'Huércal-Overa');
INSERT INTO town VALUES (341,4,'Illar');
INSERT INTO town VALUES (342,4,'Instinción');
INSERT INTO town VALUES (343,4,'Laroya');
INSERT INTO town VALUES (344,4,'Láujar de Andarax');
INSERT INTO town VALUES (345,4,'Líjar');
INSERT INTO town VALUES (346,4,'Lubrín');
INSERT INTO town VALUES (347,4,'Lucainena de las Torres');
INSERT INTO town VALUES (348,4,'Lúcar');
INSERT INTO town VALUES (349,4,'Macael');
INSERT INTO town VALUES (350,4,'María');
INSERT INTO town VALUES (351,4,'Mojácar');
INSERT INTO town VALUES (352,4,'Mojonera (La)');
INSERT INTO town VALUES (353,4,'Nacimiento');
INSERT INTO town VALUES (354,4,'Níjar');
INSERT INTO town VALUES (355,4,'Ohanes');
INSERT INTO town VALUES (356,4,'Olula de Castro');
INSERT INTO town VALUES (357,4,'Olula del Río');
INSERT INTO town VALUES (358,4,'Oria');
INSERT INTO town VALUES (359,4,'Padules');
INSERT INTO town VALUES (360,4,'Partaloa');
INSERT INTO town VALUES (361,4,'Paterna del Río');
INSERT INTO town VALUES (362,4,'Pechina');
INSERT INTO town VALUES (363,4,'Pulpí');
INSERT INTO town VALUES (364,4,'Purchena');
INSERT INTO town VALUES (365,4,'Rágol');
INSERT INTO town VALUES (366,4,'Rioja');
INSERT INTO town VALUES (367,4,'Roquetas de Mar');
INSERT INTO town VALUES (368,4,'Santa Cruz de Marchena');
INSERT INTO town VALUES (369,4,'Santa Fe de Mondújar');
INSERT INTO town VALUES (370,4,'Senés');
INSERT INTO town VALUES (371,4,'Serón');
INSERT INTO town VALUES (372,4,'Sierro');
INSERT INTO town VALUES (373,4,'Somontín');
INSERT INTO town VALUES (374,4,'Sorbas');
INSERT INTO town VALUES (375,4,'Suflí');
INSERT INTO town VALUES (376,4,'Tabernas');
INSERT INTO town VALUES (377,4,'Taberno');
INSERT INTO town VALUES (378,4,'Tahal');
INSERT INTO town VALUES (379,4,'Terque');
INSERT INTO town VALUES (380,4,'Tíjola');
INSERT INTO town VALUES (381,4,'Tres Villas (Las)');
INSERT INTO town VALUES (382,4,'Turre');
INSERT INTO town VALUES (383,4,'Turrillas');
INSERT INTO town VALUES (384,4,'Uleila del Campo');
INSERT INTO town VALUES (385,4,'Urrácal');
INSERT INTO town VALUES (386,4,'Velefique');
INSERT INTO town VALUES (387,4,'Vélez-Blanco');
INSERT INTO town VALUES (388,4,'Vélez-Rubio');
INSERT INTO town VALUES (389,4,'Vera');
INSERT INTO town VALUES (390,4,'Viator');
INSERT INTO town VALUES (391,4,'Vícar');
INSERT INTO town VALUES (392,4,'Zurgena');
INSERT INTO town VALUES (393,5,'Adanero');
INSERT INTO town VALUES (394,5,'Adrada (La)');
INSERT INTO town VALUES (395,5,'Albornos');
INSERT INTO town VALUES (396,5,'Aldeanueva de Santa Cruz');
INSERT INTO town VALUES (397,5,'Aldeaseca');
INSERT INTO town VALUES (398,5,'Aldehuela (La)');
INSERT INTO town VALUES (399,5,'Amavida');
INSERT INTO town VALUES (400,5,'Arenal (El)');
INSERT INTO town VALUES (401,5,'Arenas de San Pedro');
INSERT INTO town VALUES (402,5,'Arevalillo');
INSERT INTO town VALUES (403,5,'Arévalo');
INSERT INTO town VALUES (404,5,'Aveinte');
INSERT INTO town VALUES (405,5,'Avellaneda');
INSERT INTO town VALUES (406,5,'Ávila');
INSERT INTO town VALUES (407,5,'Barco de Ávila (El)');
INSERT INTO town VALUES (408,5,'Barraco (El)');
INSERT INTO town VALUES (409,5,'Barromán');
INSERT INTO town VALUES (410,5,'Becedas');
INSERT INTO town VALUES (411,5,'Becedillas');
INSERT INTO town VALUES (412,5,'Bercial de Zapardiel');
INSERT INTO town VALUES (413,5,'Berlanas (Las)');
INSERT INTO town VALUES (414,5,'Bernuy-Zapardiel');
INSERT INTO town VALUES (415,5,'Berrocalejo de Aragona');
INSERT INTO town VALUES (416,5,'Blascomillán');
INSERT INTO town VALUES (417,5,'Blasconuño de Matacabras');
INSERT INTO town VALUES (418,5,'Blascosancho');
INSERT INTO town VALUES (419,5,'Bohodón (El)');
INSERT INTO town VALUES (420,5,'Bohoyo');
INSERT INTO town VALUES (421,5,'Bonilla de la Sierra');
INSERT INTO town VALUES (422,5,'Brabos');
INSERT INTO town VALUES (423,5,'Bularros');
INSERT INTO town VALUES (424,5,'Burgohondo');
INSERT INTO town VALUES (425,5,'Cabezas de Alambre');
INSERT INTO town VALUES (426,5,'Cabezas del Pozo');
INSERT INTO town VALUES (427,5,'Cabezas del Villar');
INSERT INTO town VALUES (428,5,'Cabizuela');
INSERT INTO town VALUES (429,5,'Canales');
INSERT INTO town VALUES (430,5,'Candeleda');
INSERT INTO town VALUES (431,5,'Cantiveros');
INSERT INTO town VALUES (432,5,'Cardeñosa');
INSERT INTO town VALUES (433,5,'Carrera (La)');
INSERT INTO town VALUES (434,5,'Casas del Puerto');
INSERT INTO town VALUES (435,5,'Casasola');
INSERT INTO town VALUES (436,5,'Casavieja');
INSERT INTO town VALUES (437,5,'Casillas');
INSERT INTO town VALUES (438,5,'Castellanos de Zapardiel');
INSERT INTO town VALUES (439,5,'Cebreros');
INSERT INTO town VALUES (440,5,'Cepeda la Mora');
INSERT INTO town VALUES (441,5,'Chamartín');
INSERT INTO town VALUES (442,5,'Cillán');
INSERT INTO town VALUES (443,5,'Cisla');
INSERT INTO town VALUES (444,5,'Colilla (La)');
INSERT INTO town VALUES (445,5,'Collado de Contreras');
INSERT INTO town VALUES (446,5,'Collado del Mirón');
INSERT INTO town VALUES (447,5,'Constanzana');
INSERT INTO town VALUES (448,5,'Crespos');
INSERT INTO town VALUES (449,5,'Cuevas del Valle');
INSERT INTO town VALUES (450,5,'Diego del Carpio');
INSERT INTO town VALUES (451,5,'Donjimeno');
INSERT INTO town VALUES (452,5,'Donvidas');
INSERT INTO town VALUES (453,5,'Espinosa de los Caballeros');
INSERT INTO town VALUES (454,5,'Flores de Ávila');
INSERT INTO town VALUES (455,5,'Fontiveros');
INSERT INTO town VALUES (456,5,'Fresnedilla');
INSERT INTO town VALUES (457,5,'Fresno (El)');
INSERT INTO town VALUES (458,5,'Fuente el Saúz');
INSERT INTO town VALUES (459,5,'Fuentes de Año');
INSERT INTO town VALUES (460,5,'Gallegos de Altamiros');
INSERT INTO town VALUES (461,5,'Gallegos de Sobrinos');
INSERT INTO town VALUES (462,5,'Garganta del Villar');
INSERT INTO town VALUES (463,5,'Gavilanes');
INSERT INTO town VALUES (464,5,'Gemuño');
INSERT INTO town VALUES (465,5,'Gil García');
INSERT INTO town VALUES (466,5,'Gilbuena');
INSERT INTO town VALUES (467,5,'Gimialcón');
INSERT INTO town VALUES (468,5,'Gotarrendura');
INSERT INTO town VALUES (469,5,'Grandes y San Martín');
INSERT INTO town VALUES (470,5,'Guisando');
INSERT INTO town VALUES (471,5,'Gutierre-Muñoz');
INSERT INTO town VALUES (472,5,'Hernansancho');
INSERT INTO town VALUES (473,5,'Herradón de Pinares');
INSERT INTO town VALUES (474,5,'Herreros de Suso');
INSERT INTO town VALUES (475,5,'Higuera de las Dueñas');
INSERT INTO town VALUES (476,5,'Hija de Dios (La)');
INSERT INTO town VALUES (477,5,'Horcajada (La)');
INSERT INTO town VALUES (478,5,'Horcajo de las Torres');
INSERT INTO town VALUES (479,5,'Hornillo (El)');
INSERT INTO town VALUES (480,5,'Hoyo de Pinares (El)');
INSERT INTO town VALUES (481,5,'Hoyocasero');
INSERT INTO town VALUES (482,5,'Hoyorredondo');
INSERT INTO town VALUES (483,5,'Hoyos de Miguel Muñoz');
INSERT INTO town VALUES (484,5,'Hoyos del Collado');
INSERT INTO town VALUES (485,5,'Hoyos del Espino');
INSERT INTO town VALUES (486,5,'Hurtumpascual');
INSERT INTO town VALUES (487,5,'Junciana');
INSERT INTO town VALUES (488,5,'Langa');
INSERT INTO town VALUES (489,5,'Lanzahíta');
INSERT INTO town VALUES (490,5,'Llanos de Tormes (Los)');
INSERT INTO town VALUES (491,5,'Losar del Barco (El)');
INSERT INTO town VALUES (492,5,'Madrigal de las Altas Torres');
INSERT INTO town VALUES (493,5,'Maello');
INSERT INTO town VALUES (494,5,'Malpartida de Corneja');
INSERT INTO town VALUES (495,5,'Mamblas');
INSERT INTO town VALUES (496,5,'Mancera de Arriba');
INSERT INTO town VALUES (497,5,'Manjabálago');
INSERT INTO town VALUES (498,5,'Marlín');
INSERT INTO town VALUES (499,5,'Martiherrero');
INSERT INTO town VALUES (500,5,'Martínez');
INSERT INTO town VALUES (501,5,'Mediana de Voltoya');
INSERT INTO town VALUES (502,5,'Medinilla');
INSERT INTO town VALUES (503,5,'Mengamuñoz');
INSERT INTO town VALUES (504,5,'Mesegar de Corneja');
INSERT INTO town VALUES (505,5,'Mijares');
INSERT INTO town VALUES (506,5,'Mingorría');
INSERT INTO town VALUES (507,5,'Mirón (El)');
INSERT INTO town VALUES (508,5,'Mironcillo');
INSERT INTO town VALUES (509,5,'Mirueña de los Infanzones');
INSERT INTO town VALUES (510,5,'Mombeltrán');
INSERT INTO town VALUES (511,5,'Monsalupe');
INSERT INTO town VALUES (512,5,'Moraleja de Matacabras');
INSERT INTO town VALUES (513,5,'Muñana');
INSERT INTO town VALUES (514,5,'Muñico');
INSERT INTO town VALUES (515,5,'Muñogalindo');
INSERT INTO town VALUES (516,5,'Muñogrande');
INSERT INTO town VALUES (517,5,'Muñomer del Peco');
INSERT INTO town VALUES (518,5,'Muñopepe');
INSERT INTO town VALUES (519,5,'Muñosancho');
INSERT INTO town VALUES (520,5,'Muñotello');
INSERT INTO town VALUES (521,5,'Narrillos del Álamo');
INSERT INTO town VALUES (522,5,'Narrillos del Rebollar');
INSERT INTO town VALUES (523,5,'Narros de Saldueña');
INSERT INTO town VALUES (524,5,'Narros del Castillo');
INSERT INTO town VALUES (525,5,'Narros del Puerto');
INSERT INTO town VALUES (526,5,'Nava de Arévalo');
INSERT INTO town VALUES (527,5,'Nava del Barco');
INSERT INTO town VALUES (528,5,'Navacepedilla de Corneja');
INSERT INTO town VALUES (529,5,'Navadijos');
INSERT INTO town VALUES (530,5,'Navaescurial');
INSERT INTO town VALUES (531,5,'Navahondilla');
INSERT INTO town VALUES (532,5,'Navalacruz');
INSERT INTO town VALUES (533,5,'Navalmoral');
INSERT INTO town VALUES (534,5,'Navalonguilla');
INSERT INTO town VALUES (535,5,'Navalosa');
INSERT INTO town VALUES (536,5,'Navalperal de Pinares');
INSERT INTO town VALUES (537,5,'Navalperal de Tormes');
INSERT INTO town VALUES (538,5,'Navaluenga');
INSERT INTO town VALUES (539,5,'Navaquesera');
INSERT INTO town VALUES (540,5,'Navarredonda de Gredos');
INSERT INTO town VALUES (541,5,'Navarredondilla');
INSERT INTO town VALUES (542,5,'Navarrevisca');
INSERT INTO town VALUES (543,5,'Navas del Marqués (Las)');
INSERT INTO town VALUES (544,5,'Navatalgordo');
INSERT INTO town VALUES (545,5,'Navatejares');
INSERT INTO town VALUES (546,5,'Neila de San Miguel');
INSERT INTO town VALUES (547,5,'Niharra');
INSERT INTO town VALUES (548,5,'Ojos-Albos');
INSERT INTO town VALUES (549,5,'Orbita');
INSERT INTO town VALUES (550,5,'Oso (El)');
INSERT INTO town VALUES (551,5,'Padiernos');
INSERT INTO town VALUES (552,5,'Pajares de Adaja');
INSERT INTO town VALUES (553,5,'Palacios de Goda');
INSERT INTO town VALUES (554,5,'Papatrigo');
INSERT INTO town VALUES (555,5,'Parral (El)');
INSERT INTO town VALUES (556,5,'Pascualcobo');
INSERT INTO town VALUES (557,5,'Pedro Bernardo');
INSERT INTO town VALUES (558,5,'Pedro-Rodríguez');
INSERT INTO town VALUES (559,5,'Peguerinos');
INSERT INTO town VALUES (560,5,'Peñalba de Ávila');
INSERT INTO town VALUES (561,5,'Piedrahíta');
INSERT INTO town VALUES (562,5,'Piedralaves');
INSERT INTO town VALUES (563,5,'Poveda');
INSERT INTO town VALUES (564,5,'Poyales del Hoyo');
INSERT INTO town VALUES (565,5,'Pozanco');
INSERT INTO town VALUES (566,5,'Pradosegar');
INSERT INTO town VALUES (567,5,'Puerto Castilla');
INSERT INTO town VALUES (568,5,'Rasueros');
INSERT INTO town VALUES (569,5,'Riocabado');
INSERT INTO town VALUES (570,5,'Riofrío');
INSERT INTO town VALUES (571,5,'Rivilla de Barajas');
INSERT INTO town VALUES (572,5,'Salobral');
INSERT INTO town VALUES (573,5,'Salvadiós');
INSERT INTO town VALUES (574,5,'San Bartolomé de Béjar');
INSERT INTO town VALUES (575,5,'San Bartolomé de Corneja');
INSERT INTO town VALUES (576,5,'San Bartolomé de Pinares');
INSERT INTO town VALUES (577,5,'San Esteban de los Patos');
INSERT INTO town VALUES (578,5,'San Esteban de Zapardiel');
INSERT INTO town VALUES (579,5,'San Esteban del Valle');
INSERT INTO town VALUES (580,5,'San García de Ingelmos');
INSERT INTO town VALUES (581,5,'San Juan de Gredos');
INSERT INTO town VALUES (582,5,'San Juan de la Encinilla');
INSERT INTO town VALUES (583,5,'San Juan de la Nava');
INSERT INTO town VALUES (584,5,'San Juan del Molinillo');
INSERT INTO town VALUES (585,5,'San Juan del Olmo');
INSERT INTO town VALUES (586,5,'San Lorenzo de Tormes');
INSERT INTO town VALUES (587,5,'San Martín de la Vega del Alberche');
INSERT INTO town VALUES (588,5,'San Martín del Pimpollar');
INSERT INTO town VALUES (589,5,'San Miguel de Corneja');
INSERT INTO town VALUES (590,5,'San Miguel de Serrezuela');
INSERT INTO town VALUES (591,5,'San Pascual');
INSERT INTO town VALUES (592,5,'San Pedro del Arroyo');
INSERT INTO town VALUES (593,5,'San Vicente de Arévalo');
INSERT INTO town VALUES (594,5,'Sanchidrián');
INSERT INTO town VALUES (595,5,'Sanchorreja');
INSERT INTO town VALUES (596,5,'Santa Cruz de Pinares');
INSERT INTO town VALUES (597,5,'Santa Cruz del Valle');
INSERT INTO town VALUES (598,5,'Santa María de los Caballeros');
INSERT INTO town VALUES (599,5,'Santa María del Arroyo');
INSERT INTO town VALUES (600,5,'Santa María del Berrocal');
INSERT INTO town VALUES (601,5,'Santa María del Cubillo');
INSERT INTO town VALUES (602,5,'Santa María del Tiétar');
INSERT INTO town VALUES (603,5,'Santiago del Collado');
INSERT INTO town VALUES (604,5,'Santiago del Tormes');
INSERT INTO town VALUES (605,5,'Santo Domingo de las Posadas');
INSERT INTO town VALUES (606,5,'Santo Tomé de Zabarcos');
INSERT INTO town VALUES (607,5,'Serrada (La)');
INSERT INTO town VALUES (608,5,'Serranillos');
INSERT INTO town VALUES (609,5,'Sigeres');
INSERT INTO town VALUES (610,5,'Sinlabajos');
INSERT INTO town VALUES (611,5,'Solana de Ávila');
INSERT INTO town VALUES (612,5,'Solana de Rioalmar');
INSERT INTO town VALUES (613,5,'Solosancho');
INSERT INTO town VALUES (614,5,'Sotalbo');
INSERT INTO town VALUES (615,5,'Sotillo de la Adrada');
INSERT INTO town VALUES (616,5,'Tiemblo (El)');
INSERT INTO town VALUES (617,5,'Tiñosillos');
INSERT INTO town VALUES (618,5,'Tolbaños');
INSERT INTO town VALUES (619,5,'Tormellas');
INSERT INTO town VALUES (620,5,'Tornadizos de Ávila');
INSERT INTO town VALUES (621,5,'Torre (La)');
INSERT INTO town VALUES (622,5,'Tórtoles');
INSERT INTO town VALUES (623,5,'Umbrías');
INSERT INTO town VALUES (624,5,'Vadillo de la Sierra');
INSERT INTO town VALUES (625,5,'Valdecasa');
INSERT INTO town VALUES (626,5,'Vega de Santa María');
INSERT INTO town VALUES (627,5,'Velayos');
INSERT INTO town VALUES (628,5,'Villaflor');
INSERT INTO town VALUES (629,5,'Villafranca de la Sierra');
INSERT INTO town VALUES (630,5,'Villanueva de Ávila');
INSERT INTO town VALUES (631,5,'Villanueva de Gómez');
INSERT INTO town VALUES (632,5,'Villanueva del Aceral');
INSERT INTO town VALUES (633,5,'Villanueva del Campillo');
INSERT INTO town VALUES (634,5,'Villar de Corneja');
INSERT INTO town VALUES (635,5,'Villarejo del Valle');
INSERT INTO town VALUES (636,5,'Villatoro');
INSERT INTO town VALUES (637,5,'Viñegra de Moraña');
INSERT INTO town VALUES (638,5,'Vita');
INSERT INTO town VALUES (639,5,'Zapardiel de la Cañada');
INSERT INTO town VALUES (640,5,'Zapardiel de la Ribera');
INSERT INTO town VALUES (641,6,'Acedera');
INSERT INTO town VALUES (642,6,'Aceuchal');
INSERT INTO town VALUES (643,6,'Ahillones');
INSERT INTO town VALUES (644,6,'Alange');
INSERT INTO town VALUES (645,6,'Albuera (La)');
INSERT INTO town VALUES (646,6,'Alburquerque');
INSERT INTO town VALUES (647,6,'Alconchel');
INSERT INTO town VALUES (648,6,'Alconera');
INSERT INTO town VALUES (649,6,'Aljucén');
INSERT INTO town VALUES (650,6,'Almendral');
INSERT INTO town VALUES (651,6,'Almendralejo');
INSERT INTO town VALUES (652,6,'Arroyo de San Serván');
INSERT INTO town VALUES (653,6,'Atalaya');
INSERT INTO town VALUES (654,6,'Azuaga');
INSERT INTO town VALUES (655,6,'Badajoz');
INSERT INTO town VALUES (656,6,'Barcarrota');
INSERT INTO town VALUES (657,6,'Baterno');
INSERT INTO town VALUES (658,6,'Benquerencia de la Serena');
INSERT INTO town VALUES (659,6,'Berlanga');
INSERT INTO town VALUES (660,6,'Bienvenida');
INSERT INTO town VALUES (661,6,'Bodonal de la Sierra');
INSERT INTO town VALUES (662,6,'Burguillos del Cerro');
INSERT INTO town VALUES (663,6,'Cabeza del Buey');
INSERT INTO town VALUES (664,6,'Cabeza la Vaca');
INSERT INTO town VALUES (665,6,'Calamonte');
INSERT INTO town VALUES (666,6,'Calera de León');
INSERT INTO town VALUES (667,6,'Calzadilla de los Barros');
INSERT INTO town VALUES (668,6,'Campanario');
INSERT INTO town VALUES (669,6,'Campillo de Llerena');
INSERT INTO town VALUES (670,6,'Capilla');
INSERT INTO town VALUES (671,6,'Carmonita');
INSERT INTO town VALUES (672,6,'Carrascalejo (El)');
INSERT INTO town VALUES (673,6,'Casas de Don Pedro');
INSERT INTO town VALUES (674,6,'Casas de Reina');
INSERT INTO town VALUES (675,6,'Castilblanco');
INSERT INTO town VALUES (676,6,'Castuera');
INSERT INTO town VALUES (677,6,'Cheles');
INSERT INTO town VALUES (678,6,'Codosera (La)');
INSERT INTO town VALUES (679,6,'Cordobilla de Lácara');
INSERT INTO town VALUES (680,6,'Coronada (La)');
INSERT INTO town VALUES (681,6,'Corte de Peleas');
INSERT INTO town VALUES (682,6,'Cristina');
INSERT INTO town VALUES (683,6,'Don Álvaro');
INSERT INTO town VALUES (684,6,'Don Benito');
INSERT INTO town VALUES (685,6,'Entrín Bajo');
INSERT INTO town VALUES (686,6,'Esparragalejo');
INSERT INTO town VALUES (687,6,'Esparragosa de la Serena');
INSERT INTO town VALUES (688,6,'Esparragosa de Lares');
INSERT INTO town VALUES (689,6,'Feria');
INSERT INTO town VALUES (690,6,'Fregenal de la Sierra');
INSERT INTO town VALUES (691,6,'Fuenlabrada de los Montes');
INSERT INTO town VALUES (692,6,'Fuente de Cantos');
INSERT INTO town VALUES (693,6,'Fuente del Arco');
INSERT INTO town VALUES (694,6,'Fuente del Maestre');
INSERT INTO town VALUES (695,6,'Fuentes de León');
INSERT INTO town VALUES (696,6,'Garbayuela');
INSERT INTO town VALUES (697,6,'Garlitos');
INSERT INTO town VALUES (698,6,'Garrovilla (La)');
INSERT INTO town VALUES (699,6,'Granja de Torrehermosa');
INSERT INTO town VALUES (700,6,'Guareña');
INSERT INTO town VALUES (701,6,'Haba (La)');
INSERT INTO town VALUES (702,6,'Helechosa de los Montes');
INSERT INTO town VALUES (703,6,'Herrera del Duque');
INSERT INTO town VALUES (704,6,'Higuera de la Serena');
INSERT INTO town VALUES (705,6,'Higuera de Llerena');
INSERT INTO town VALUES (706,6,'Higuera de Vargas');
INSERT INTO town VALUES (707,6,'Higuera la Real');
INSERT INTO town VALUES (708,6,'Hinojosa del Valle');
INSERT INTO town VALUES (709,6,'Hornachos');
INSERT INTO town VALUES (710,6,'Jerez de los Caballeros');
INSERT INTO town VALUES (711,6,'Lapa (La)');
INSERT INTO town VALUES (712,6,'Llera');
INSERT INTO town VALUES (713,6,'Llerena');
INSERT INTO town VALUES (714,6,'Lobón');
INSERT INTO town VALUES (715,6,'Magacela');
INSERT INTO town VALUES (716,6,'Maguilla');
INSERT INTO town VALUES (717,6,'Malcocinado');
INSERT INTO town VALUES (718,6,'Malpartida de la Serena');
INSERT INTO town VALUES (719,6,'Manchita');
INSERT INTO town VALUES (720,6,'Medellín');
INSERT INTO town VALUES (721,6,'Medina de las Torres');
INSERT INTO town VALUES (722,6,'Mengabril');
INSERT INTO town VALUES (723,6,'Mérida');
INSERT INTO town VALUES (724,6,'Mirandilla');
INSERT INTO town VALUES (725,6,'Monesterio');
INSERT INTO town VALUES (726,6,'Montemolín');
INSERT INTO town VALUES (727,6,'Monterrubio de la Serena');
INSERT INTO town VALUES (728,6,'Montijo');
INSERT INTO town VALUES (729,6,'Morera (La)');
INSERT INTO town VALUES (730,6,'Nava de Santiago (La)');
INSERT INTO town VALUES (731,6,'Navalvillar de Pela');
INSERT INTO town VALUES (732,6,'Nogales');
INSERT INTO town VALUES (733,6,'Oliva de la Frontera');
INSERT INTO town VALUES (734,6,'Oliva de Mérida');
INSERT INTO town VALUES (735,6,'Olivenza');
INSERT INTO town VALUES (736,6,'Orellana de la Sierra');
INSERT INTO town VALUES (737,6,'Orellana la Vieja');
INSERT INTO town VALUES (738,6,'Palomas');
INSERT INTO town VALUES (739,6,'Parra (La)');
INSERT INTO town VALUES (740,6,'Peñalsordo');
INSERT INTO town VALUES (741,6,'Peraleda del Zaucejo');
INSERT INTO town VALUES (742,6,'Puebla de Alcocer');
INSERT INTO town VALUES (743,6,'Puebla de la Calzada');
INSERT INTO town VALUES (744,6,'Puebla de la Reina');
INSERT INTO town VALUES (745,6,'Puebla de Obando');
INSERT INTO town VALUES (746,6,'Puebla de Sancho Pérez');
INSERT INTO town VALUES (747,6,'Puebla del Maestre');
INSERT INTO town VALUES (748,6,'Puebla del Prior');
INSERT INTO town VALUES (749,6,'Pueblonuevo del Guadiana');
INSERT INTO town VALUES (750,6,'Quintana de la Serena');
INSERT INTO town VALUES (751,6,'Reina');
INSERT INTO town VALUES (752,6,'Rena');
INSERT INTO town VALUES (753,6,'Retamal de Llerena');
INSERT INTO town VALUES (754,6,'Ribera del Fresno');
INSERT INTO town VALUES (755,6,'Risco');
INSERT INTO town VALUES (756,6,'Roca de la Sierra (La)');
INSERT INTO town VALUES (757,6,'Salvaleón');
INSERT INTO town VALUES (758,6,'Salvatierra de los Barros');
INSERT INTO town VALUES (759,6,'San Pedro de Mérida');
INSERT INTO town VALUES (760,6,'San Vicente de Alcántara');
INSERT INTO town VALUES (761,6,'Sancti-Spíritus');
INSERT INTO town VALUES (762,6,'Santa Amalia');
INSERT INTO town VALUES (763,6,'Santa Marta');
INSERT INTO town VALUES (764,6,'Santos de Maimona (Los)');
INSERT INTO town VALUES (765,6,'Segura de León');
INSERT INTO town VALUES (766,6,'Siruela');
INSERT INTO town VALUES (767,6,'Solana de los Barros');
INSERT INTO town VALUES (768,6,'Talarrubias');
INSERT INTO town VALUES (769,6,'Talavera la Real');
INSERT INTO town VALUES (770,6,'Táliga');
INSERT INTO town VALUES (771,6,'Tamurejo');
INSERT INTO town VALUES (772,6,'Torre de Miguel Sesmero');
INSERT INTO town VALUES (773,6,'Torremayor');
INSERT INTO town VALUES (774,6,'Torremejía');
INSERT INTO town VALUES (775,6,'Trasierra');
INSERT INTO town VALUES (776,6,'Trujillanos');
INSERT INTO town VALUES (777,6,'Usagre');
INSERT INTO town VALUES (778,6,'Valdecaballeros');
INSERT INTO town VALUES (779,6,'Valdelacalzada');
INSERT INTO town VALUES (780,6,'Valdetorres');
INSERT INTO town VALUES (781,6,'Valencia de las Torres');
INSERT INTO town VALUES (782,6,'Valencia del Mombuey');
INSERT INTO town VALUES (783,6,'Valencia del Ventoso');
INSERT INTO town VALUES (784,6,'Valle de la Serena');
INSERT INTO town VALUES (785,6,'Valle de Matamoros');
INSERT INTO town VALUES (786,6,'Valle de Santa Ana');
INSERT INTO town VALUES (787,6,'Valverde de Burguillos');
INSERT INTO town VALUES (788,6,'Valverde de Leganés');
INSERT INTO town VALUES (789,6,'Valverde de Llerena');
INSERT INTO town VALUES (790,6,'Valverde de Mérida');
INSERT INTO town VALUES (791,6,'Villafranca de los Barros');
INSERT INTO town VALUES (792,6,'Villagarcía de la Torre');
INSERT INTO town VALUES (793,6,'Villagonzalo');
INSERT INTO town VALUES (794,6,'Villalba de los Barros');
INSERT INTO town VALUES (795,6,'Villanueva de la Serena');
INSERT INTO town VALUES (796,6,'Villanueva del Fresno');
INSERT INTO town VALUES (797,6,'Villar de Rena');
INSERT INTO town VALUES (798,6,'Villar del Rey');
INSERT INTO town VALUES (799,6,'Villarta de los Montes');
INSERT INTO town VALUES (800,6,'Zafra');
INSERT INTO town VALUES (801,6,'Zahínos');
INSERT INTO town VALUES (802,6,'Zalamea de la Serena');
INSERT INTO town VALUES (803,6,'Zarza (La)');
INSERT INTO town VALUES (804,6,'Zarza-Capilla');
INSERT INTO town VALUES (805,7,'Alaior');
INSERT INTO town VALUES (806,7,'Alaró');
INSERT INTO town VALUES (807,7,'Alcúdia');
INSERT INTO town VALUES (808,7,'Algaida');
INSERT INTO town VALUES (809,7,'Andratx');
INSERT INTO town VALUES (810,7,'Ariany');
INSERT INTO town VALUES (811,7,'Artà');
INSERT INTO town VALUES (812,7,'Banyalbufar');
INSERT INTO town VALUES (813,7,'Binissalem');
INSERT INTO town VALUES (814,7,'Búger');
INSERT INTO town VALUES (815,7,'Bunyola');
INSERT INTO town VALUES (816,7,'Calvià');
INSERT INTO town VALUES (817,7,'Campanet');
INSERT INTO town VALUES (818,7,'Campos');
INSERT INTO town VALUES (819,7,'Capdepera');
INSERT INTO town VALUES (820,7,'Castell (Es)');
INSERT INTO town VALUES (821,7,'Ciutadella de Menorca');
INSERT INTO town VALUES (822,7,'Consell');
INSERT INTO town VALUES (823,7,'Costitx');
INSERT INTO town VALUES (824,7,'Deyá');
INSERT INTO town VALUES (825,7,'Eivissa');
INSERT INTO town VALUES (826,7,'Escorca');
INSERT INTO town VALUES (827,7,'Esporles');
INSERT INTO town VALUES (828,7,'Estellencs');
INSERT INTO town VALUES (829,7,'Felanitx');
INSERT INTO town VALUES (830,7,'Ferreries');
INSERT INTO town VALUES (831,7,'Formentera');
INSERT INTO town VALUES (832,7,'Fornalutx');
INSERT INTO town VALUES (833,7,'Inca');
INSERT INTO town VALUES (834,7,'Lloret de Vistalegre');
INSERT INTO town VALUES (835,7,'Lloseta');
INSERT INTO town VALUES (836,7,'Llubí');
INSERT INTO town VALUES (837,7,'Llucmajor');
INSERT INTO town VALUES (838,7,'Manacor');
INSERT INTO town VALUES (839,7,'Mancor de la Vall');
INSERT INTO town VALUES (840,7,'Maó');
INSERT INTO town VALUES (841,7,'Maria de la Salut');
INSERT INTO town VALUES (842,7,'Marratxí');
INSERT INTO town VALUES (843,7,'Mercadal (Es)');
INSERT INTO town VALUES (844,7,'Migjorn Gran (Es)');
INSERT INTO town VALUES (845,7,'Montuïri');
INSERT INTO town VALUES (846,7,'Muro');
INSERT INTO town VALUES (847,7,'Palma de Mallorca');
INSERT INTO town VALUES (848,7,'Petra');
INSERT INTO town VALUES (849,7,'Pobla (Sa)');
INSERT INTO town VALUES (850,7,'Pollença');
INSERT INTO town VALUES (851,7,'Porreres');
INSERT INTO town VALUES (852,7,'Puigpunyent');
INSERT INTO town VALUES (853,7,'Salines (Ses)');
INSERT INTO town VALUES (854,7,'Sant Antoni de Portmany');
INSERT INTO town VALUES (855,7,'Sant Joan');
INSERT INTO town VALUES (856,7,'Sant Joan de Labritja');
INSERT INTO town VALUES (857,7,'Sant Josep de sa Talaia');
INSERT INTO town VALUES (858,7,'Sant Llorenç des Cardassar');
INSERT INTO town VALUES (859,7,'Sant Lluís');
INSERT INTO town VALUES (860,7,'Santa Eugènia');
INSERT INTO town VALUES (861,7,'Santa Eulalia del Río');
INSERT INTO town VALUES (862,7,'Santa Margalida');
INSERT INTO town VALUES (863,7,'Santa María del Camí');
INSERT INTO town VALUES (864,7,'Santanyí');
INSERT INTO town VALUES (865,7,'Selva');
INSERT INTO town VALUES (866,7,'Sencelles');
INSERT INTO town VALUES (867,7,'Sineu');
INSERT INTO town VALUES (868,7,'Sóller');
INSERT INTO town VALUES (869,7,'Son Servera');
INSERT INTO town VALUES (870,7,'Valldemossa');
INSERT INTO town VALUES (871,7,'Vilafranca de Bonany');
INSERT INTO town VALUES (872,8,'Abrera');
INSERT INTO town VALUES (873,8,'Aguilar de Segarra');
INSERT INTO town VALUES (874,8,'Aiguafreda');
INSERT INTO town VALUES (875,8,'Alella');
INSERT INTO town VALUES (876,8,'Alpens');
INSERT INTO town VALUES (877,8,'Ametlla del Vallès ');
INSERT INTO town VALUES (878,8,'Arenys de Mar');
INSERT INTO town VALUES (879,8,'Arenys de Munt');
INSERT INTO town VALUES (880,8,'Argençola');
INSERT INTO town VALUES (881,8,'Argentona');
INSERT INTO town VALUES (882,8,'Artés');
INSERT INTO town VALUES (883,8,'Avià');
INSERT INTO town VALUES (884,8,'Avinyó');
INSERT INTO town VALUES (885,8,'Avinyonet del Penedès');
INSERT INTO town VALUES (886,8,'Badalona');
INSERT INTO town VALUES (887,8,'Badia del Vallès');
INSERT INTO town VALUES (888,8,'Bagà');
INSERT INTO town VALUES (889,8,'Balenyà');
INSERT INTO town VALUES (890,8,'Balsareny');
INSERT INTO town VALUES (891,8,'Barberà del Vallès');
INSERT INTO town VALUES (892,8,'Barcelona');
INSERT INTO town VALUES (893,8,'Begues');
INSERT INTO town VALUES (894,8,'Bellprat');
INSERT INTO town VALUES (895,8,'Berga');
INSERT INTO town VALUES (896,8,'Bigues i Riells');
INSERT INTO town VALUES (897,8,'Borredà');
INSERT INTO town VALUES (898,8,'Bruc (El)');
INSERT INTO town VALUES (899,8,'Brull (El)');
INSERT INTO town VALUES (900,8,'Cabanyes (Les)');
INSERT INTO town VALUES (901,8,'Cabrera de Mar');
INSERT INTO town VALUES (902,8,'Cabrera deIgualada');
INSERT INTO town VALUES (903,8,'Cabrils');
INSERT INTO town VALUES (904,8,'Calaf');
INSERT INTO town VALUES (905,8,'Calders');
INSERT INTO town VALUES (906,8,'Caldes de Montbui');
INSERT INTO town VALUES (907,8,'Caldes deEstrac');
INSERT INTO town VALUES (908,8,'Calella');
INSERT INTO town VALUES (909,8,'Calldetenes');
INSERT INTO town VALUES (910,8,'Callús');
INSERT INTO town VALUES (911,8,'Calonge de Segarra');
INSERT INTO town VALUES (912,8,'Campins');
INSERT INTO town VALUES (913,8,'Canet de Mar');
INSERT INTO town VALUES (914,8,'Canovelles');
INSERT INTO town VALUES (915,8,'Cànoves i Samalús');
INSERT INTO town VALUES (916,8,'Canyelles');
INSERT INTO town VALUES (917,8,'Capellades');
INSERT INTO town VALUES (918,8,'Capolat');
INSERT INTO town VALUES (919,8,'Cardedeu');
INSERT INTO town VALUES (920,8,'Cardona');
INSERT INTO town VALUES (921,8,'Carme');
INSERT INTO town VALUES (922,8,'Casserres');
INSERT INTO town VALUES (923,8,'Castell de lAreny');
INSERT INTO town VALUES (924,8,'Castellar de nHug');
INSERT INTO town VALUES (925,8,'Castellar del Riu');
INSERT INTO town VALUES (926,8,'Castellar del Vallès');
INSERT INTO town VALUES (927,8,'Castellbell i el Vilar');
INSERT INTO town VALUES (928,8,'Castellbisbal');
INSERT INTO town VALUES (929,8,'Castellcir');
INSERT INTO town VALUES (930,8,'Castelldefels');
INSERT INTO town VALUES (931,8,'Castellet i la Gornal');
INSERT INTO town VALUES (932,8,'Castellfollit de Riubregós');
INSERT INTO town VALUES (933,8,'Castellfollit del Boix');
INSERT INTO town VALUES (934,8,'Castellgalí');
INSERT INTO town VALUES (935,8,'Castellnou de Bages');
INSERT INTO town VALUES (936,8,'Castellolí');
INSERT INTO town VALUES (937,8,'Castellterçol');
INSERT INTO town VALUES (938,8,'Castellví de la Marca');
INSERT INTO town VALUES (939,8,'Castellví de Rosanes');
INSERT INTO town VALUES (940,8,'Centelles');
INSERT INTO town VALUES (941,8,'Cercs');
INSERT INTO town VALUES (942,8,'Cerdanyola del Vallès');
INSERT INTO town VALUES (943,8,'Cervelló');
INSERT INTO town VALUES (944,8,'Collbató');
INSERT INTO town VALUES (945,8,'Collsuspina');
INSERT INTO town VALUES (946,8,'Copons');
INSERT INTO town VALUES (947,8,'Corbera de Llobregat');
INSERT INTO town VALUES (948,8,'Cornellà de Llobregat');
INSERT INTO town VALUES (949,8,'Cubelles');
INSERT INTO town VALUES (950,8,'Dosrius');
INSERT INTO town VALUES (951,8,'Esparreguera');
INSERT INTO town VALUES (952,8,'Esplugues de Llobregat');
INSERT INTO town VALUES (953,8,'Espunyola ');
INSERT INTO town VALUES (954,8,'Estany ');
INSERT INTO town VALUES (955,8,'Figaró-Montmany');
INSERT INTO town VALUES (956,8,'Fígols');
INSERT INTO town VALUES (957,8,'Fogars de la Selva');
INSERT INTO town VALUES (958,8,'Fogars de Montclús');
INSERT INTO town VALUES (959,8,'Folgueroles');
INSERT INTO town VALUES (960,8,'Fonollosa');
INSERT INTO town VALUES (961,8,'Font-rubí');
INSERT INTO town VALUES (962,8,'Franqueses del Vallès (Les)');
INSERT INTO town VALUES (963,8,'Gaià');
INSERT INTO town VALUES (964,8,'Gallifa');
INSERT INTO town VALUES (965,8,'Garriga (La)');
INSERT INTO town VALUES (966,8,'Gavà');
INSERT INTO town VALUES (967,8,'Gelida');
INSERT INTO town VALUES (968,8,'Gironella');
INSERT INTO town VALUES (969,8,'Gisclareny');
INSERT INTO town VALUES (970,8,'Granada (La)');
INSERT INTO town VALUES (971,8,'Granera');
INSERT INTO town VALUES (972,8,'Granollers');
INSERT INTO town VALUES (973,8,'Gualba');
INSERT INTO town VALUES (974,8,'Guardiola de Berguedà');
INSERT INTO town VALUES (975,8,'Gurb');
INSERT INTO town VALUES (976,8,'Hospitalet de Llobregat ');
INSERT INTO town VALUES (977,8,'Hostalets de Pierola (Els)');
INSERT INTO town VALUES (978,8,'Igualada');
INSERT INTO town VALUES (979,8,'Jorba');
INSERT INTO town VALUES (980,8,'Llacuna (La)');
INSERT INTO town VALUES (981,8,'Llagosta (La)');
INSERT INTO town VALUES (982,8,'Lliçà deAmunt');
INSERT INTO town VALUES (983,8,'Lliçà de Vall');
INSERT INTO town VALUES (984,8,'Llinars del Vallès');
INSERT INTO town VALUES (985,8,'Lluçà');
INSERT INTO town VALUES (986,8,'Malgrat de Mar');
INSERT INTO town VALUES (987,8,'Malla');
INSERT INTO town VALUES (988,8,'Manlleu');
INSERT INTO town VALUES (989,8,'Manresa');
INSERT INTO town VALUES (990,8,'Marganell');
INSERT INTO town VALUES (991,8,'Martorell');
INSERT INTO town VALUES (992,8,'Martorelles');
INSERT INTO town VALUES (993,8,'Masies de Roda (Les)');
INSERT INTO town VALUES (994,8,'Masies de Voltregà (Les)');
INSERT INTO town VALUES (995,8,'Masnou (El)');
INSERT INTO town VALUES (996,8,'Masquefa');
INSERT INTO town VALUES (997,8,'Matadepera');
INSERT INTO town VALUES (998,8,'Mataró');
INSERT INTO town VALUES (999,8,'Mediona');
INSERT INTO town VALUES (1000,8,'Moià');
